### ISSUE TITLE
E-Mail Notification for Comments

### ISSUE THREAD

**Issue by sivaa** [pythonindia/junction#10]
* The notification should to sent to the author of the proposal and reviewers.

**Comment by theskumar** [comment]
@vigneshsarma @kracekumar what is the status of this issue. PR #60 seems to implement this feature. If functionality is working we can add todo's from PR as issues to be tracked and close this major issue.

**Comment by vigneshsarma** [comment]
Yes, this is indeed done in #60. So closing this issue.
