### ISSUE TITLE
Proposal Page - Voting Link - No Redirection

### ISSUE THREAD

**Issue by sivaa** [pythonindia/junction#105]
- There is no redirection after clicking the upvote button(Not logged In -> Click on upvote -> Login redirection - This blank page appears)

![image](https://cloud.githubusercontent.com/assets/2163422/5988300/bc44f3fa-a980-11e4-824d-40711f6e1164.png)

**Comment by theskumar** [comment]
This seems to fixed in the latest dev build. Not able to reproduce.

**Comment by sivaa** [comment]
@kracekumar Can you test this and close it?

**Comment by theskumar** [comment]
This has been fixed in https://github.com/pythonindia/junction/issues/142. Closing this issue.
