### ISSUE TITLE
Proposal Voting - Count Mismatch

### ISSUE THREAD

**Issue by sivaa** [pythonindia/junction#106]
- Mismatch between list page and details page.
- In the detail page, the Vote count shows ZERO without login and shows as ONE after login.

![image](https://cloud.githubusercontent.com/assets/2163422/5988296/9f4e0ff2-a980-11e4-91d8-58e45b57db47.png)

![image](https://cloud.githubusercontent.com/assets/2163422/5988305/f8d2d01c-a980-11e4-9a3f-a7af0a0505bd.png)

**Comment by kracekumar** [comment]
Fixed in https://github.com/pythonindia/junction/commit/ccae762499b8820f0568d5d6ac5aae7a1ed1d3c6
