### ISSUE TITLE
Proposal Detail - Voting - Highlighting

### ISSUE THREAD

**Issue by sivaa** [pythonindia/junction#108]
I have voted for this proposal. But it is not highlighted.

![image](https://cloud.githubusercontent.com/assets/2163422/5988344/57322e90-a982-11e4-8a73-238dc4a9a1ed.png)

**Comment by mudassir0909** [comment]
@kracekumar Let me know when the active class is added, so that I can style

**Comment by kracekumar** [comment]
It is done.
