### ISSUE TITLE
When we add CFP link in FB/twitter is show info about junction instead of CFP info

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/junction#122]
When we add CFP link( like pybelgaum http://junction.pybelgaum.org/pybelgaum/proposals/) in Facebook it show information about junction software in place of conference page.(Attached screen shot from facebook). 
This is not give right impression about the CFP as it looks from outside advertisement from junction software.
This need to be fixed ASAP.
![junction_bug_onfb](https://cloud.githubusercontent.com/assets/316253/6035499/a9c86838-ac5a-11e4-8ae6-b40b47d62b9b.png)

**Comment by kracekumar** [comment]
New look in list page

![screen shot 2015-02-06 at 2 15 31 am](https://cloud.githubusercontent.com/assets/311929/6068922/2906e63c-ada6-11e4-909d-a5ae1522fecb.png)

New look in detail page
![screen shot 2015-02-06 at 2 17 17 am](https://cloud.githubusercontent.com/assets/311929/6068945/53b0a8b4-ada6-11e4-9730-9a07e94effd0.png)
