### ISSUE TITLE
add support for asynchronous task queues

### ISSUE THREAD

**Issue by bhanuvrat** [pythonindia/junction#123]
configure celery to run with redis as backend.
in order to help with background jobs like sending notification / bulk emails.

**Comment by sivaa** [comment]
+1. We should do this in next milestone.

**Comment by theskumar** [comment]
https://github.com/pythonindia/junction/issues/7 is related i guess.

**Comment by theskumar** [comment]
This is closed in https://github.com/pythonindia/junction/pull/129
