### ISSUE TITLE
deployment scripts

### ISSUE THREAD

**Issue by bhanuvrat** [pythonindia/junction#125]
how is the project currently being deployed in production?
would ansible based deployment script help in the process?

**Comment by theskumar** [comment]
We are planning to have one instance of this auto deployed on heroku from our .travis ci from `master` for QA purposes. 

@kracekumar can fill you in more what's that the plan for production setup. In my view, an ansible script for ubuntu based server should be a good way to go.

**Comment by kracekumar** [comment]
@vigneshsarma Has some plans, he'll shed light into this.

**Comment by vigneshsarma** [comment]
I am planing to use saltstack <http://saltstack.com/>.

We will have to use it as part of some other setup(Along with other
applications) as well as an independent deployment. I am figuring out how
best to do that.

Other suggestion are welcome!!!

**Comment by bhanuvrat** [comment]
@vigneshsarma saltstack is supercool.
IMO ansible would be easier and simpler, for a relatively small application like junction.
Thoughts?

**Comment by vigneshsarma** [comment]
@bhanuvrat I have tried Ansible, and agree with you that it is easier to setup than saltstack.

But we are planning to automate the whole pssi/pycon india infrastructure, Junction is just one piece of the puzzle. It is in this context that I think saltstack might be a better choice.

**Comment by kracekumar** [comment]
Here is the junction specific deployment https://github.com/pythonindia/magudi/blob/master/salt/roots/junction/.

**Comment by theskumar** [comment]
@kracekumar @vigneshsarma this is neat +1. I think, providing this link to Readme should be enough to close this particular issue. @bhanuvrat ?

**Comment by bhanuvrat** [comment]
@theskumar yup this is cool !!
