### ISSUE TITLE
bug: datatable is not a defined function 

### ISSUE THREAD

**Issue by theskumar** [pythonindia/junction#128]
on http://junction.pybelgaum.org/pybelgaum/proposals/
![screen](https://www.dropbox.com/s/uxjidu918a9mi0n/Screenshot%202015-02-06%2013.24.34.png?dl=1)

**Comment by bhanuvrat** [comment]
@theskumar DataTable's js library is not referenced hence the error.
btw, I don't see why DataTable is needed on this page ... how and where is it being used?

**Comment by theskumar** [comment]
It seems it just need to be checked and removed. I don't it being used anywhere.





Saurabh Kumar

https://keybase.io/theskumar








On Saturday, Feb 21, 2015 at 1:23 pm, Anuvrat Parashar <notifications@github.com>, wrote:
@theskumar DataTable's js library is not referenced hence the error.
btw, I don't see why DataTable is needed on this page ... how and where is it being used?

**Comment by vnbang2003** [comment]
@theskumar : if not able to duplicate. Can you please close the bug ?
