### ISSUE TITLE
add google analytics intergration

### ISSUE THREAD

**Issue by theskumar** [pythonindia/junction#130]
If `GOOGLE_ANALTICS_ID` environment variable is set, google tracker code should be added to `base.html`

**Comment by kracekumar** [comment]
+1

On Sat, Feb 7, 2015 at 4:15 PM, Saurabh Kumar <notifications@github.com>
wrote:

> If google_analytics environment variable is set, google tracker code
> should be added to base.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pythonindia/junction/issues/130>.
>



-- 
Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521

**Comment by theskumar** [comment]
You can review and close the pull request :point_up:
