### ISSUE TITLE
Proposal Comments - Up/Down Vote Button should be highligted

### ISSUE THREAD

**Issue by sivaa** [pythonindia/junction#137]
The fix could be much similar to proposal detail page vote button fix.

![image](https://cloud.githubusercontent.com/assets/2163422/6097220/7431ad3c-afda-11e4-96b6-42c98fe74d19.png)

**Comment by theskumar** [comment]
This will a huge number of database calls, if there many comments for a proposal. Either we paginate the comments or add some sort of caching to maintain the sanity.

Caching per user is going to be little costly business.

**Comment by psykrsna** [comment]
I am working on this.

**Comment by theskumar** [comment]
Thanks :+1:
