### ISSUE TITLE
Proposal Detail - Section Headings should be higglighted

### ISSUE THREAD

**Issue by sivaa** [pythonindia/junction#138]
It would be nice if we have some additional highlighting with different font, color, bold text, separators, more spaces etc...
![image](https://cloud.githubusercontent.com/assets/2163422/6097227/e7944a32-afda-11e4-9864-a38227bc9b9f.png)

**Comment by Aayush-Kasurde** [comment]
Can anyone please close this issue as PR #232 is merged?
