### ISSUE TITLE
allow custom user-defined proposal tags

### ISSUE THREAD

**Issue by sivaa** [pythonindia/junction#139]
Currently there is no way for the proposal author to define the custom tags. For example, if someone proposes a talk called "Performance Tuning in Django ORM", the  possible tags could be django, performance etc...
# Persistence
- TagMaster(Tag Name with Audit Fields)
- Proposal Tags(proposal and tag FKs)
# Usage
- The tags should have auto-complete feature
- If the tag is not found, it should have automatically created in the TagMaster(Created By - Propsal Author).
- Maximum of 3 tags can be used per proposal.
- Duplicate tags in the proposal is not allowed.
- The tags can be removed in the detail page
- The tags should appear in the proposal detail and list pages.
- In the proposal list page, It should be right aligned before the author name and date with the different color/font.
- Clicking on these tags should filter the proposals with the selected tag

**Comment by theskumar** [comment]
+1 for this feature.

It seems this issue is related: https://github.com/pythonindia/junction/issues/88 and should be considered as well.

**Comment by kracekumar** [comment]
How about using tags from stackoverflow ? We can make http call to stackoverflow to find them?

**Comment by ananyo2012** [comment]
@palnabarun @pradyunsg Do you think tags are useful in a proposal ? CPFs are not usually the source of content until they are published, before which it is mostly read by reviewers. 

Presently tags are there for proposal sections and types which can be created only by the admin, not by the submitter.

**Comment by pradyunsg** [comment]
I haven't seen a CFP use tags. I don't *know* this from experience but my intuition tells me that it's best to avoid it.

**Comment by ananyo2012** [comment]
Yeah that's my feeling as well. @palnabarun shall we close this ?

**Comment by palnabarun** [comment]
Sure. Same thoughts. Giving that flexibility is kind of a rabbit-hole it seems.
