### ISSUE TITLE
add ability to favorite a proposal

### ISSUE THREAD

**Issue by sivaa** [pythonindia/junction#14]
- Autheticated users should able to mark proposals as their favorite in the detail page.
- All the marked proposals should be listed in a separate section called "My Favorites" in the proposal list(similar to "My Proposals")
- If there no favorite proposals, "My Proposals" shouldn't visible on the proposal list page
- The data should be stored in a separate model called "FavoriteProposal" with user, proposal FKs along with audit fields.
- They also should be able to remove a proposal from favorite from the "My Favorites" list directly with "x" link(or similar) or from the proposal detail page.
- Sample favorite icon.

![image](https://cloud.githubusercontent.com/assets/2163422/6097199/dee37198-afd9-11e4-876e-2bde39de95fe.png)

**Comment by theskumar** [comment]
@sivaa can we description add to it, please?

**Comment by sivaa** [comment]
@theskumar updated.

**Comment by theskumar** [comment]
@sivaa Why not have it as a subscribe feature. Similar to the way you can subscribe to any issue on github. The UI can live next to proposal meta in the detail view. ![a](https://www.dropbox.com/s/68qck1s9pyztzs9/Screenshot%202015-02-16%2010.09.34.png?dl=1)

We can use https://github.com/justquick/django-activity-stream to provide notifications for all subscribed proposals + other things. 

If you like we can have view to display all the subscribed proposals, it can be in the same view as the notifications view. Something like this ![b](https://www.dropbox.com/s/fazcsse4u73c2yb/Screenshot%202015-02-16%2010.13.14.png?dl=1)

PS: There is no fun having it on list view as the user have not seen it properly.

**Comment by sivaa** [comment]
@theskumar Yep. This idea looks cool than the classical favorite options. @kracekumar Any suggestions?

**Comment by kracekumar** [comment]
Looks good. But we will end up sending lot of emails. These notification should be carefully crafted because reviewers comments shouldn't be emailed to subcribers :-). This can hold on for a bit. I think we can have this in next milestone ?

**Comment by pythonhacker** [comment]
Can we triage and close or specify action points for issues older than a year ?

**Comment by pythonhacker** [comment]
Sending emails for favorited proposals is overkill for a software like this. It is closer to *feature-creep* than a good feature. 

The idea of marking proposals as favorite is good. But these can just show up separately in a section once user logs in rather than adding an email workflow.

My suggestion is to triage(close) this issue - think about this - and file a fresh one.

**Comment by theskumar** [comment]
I'm in favour of closing this one, without proper planning it doesn't provide much value, given lifecycle of the CFP.
