### ISSUE TITLE
Proposal List - Markdown Syntax

### ISSUE THREAD

**Issue by sivaa** [pythonindia/junction#140]
We can't allow the markdown syntax or rendering on the proposal list page.

![image](https://cloud.githubusercontent.com/assets/2163422/6097258/1058138e-afdd-11e4-8fa4-4426368b7436.png)

@kracekumar @theskumar Any ideas? Can we remove just the syntax?

**Comment by theskumar** [comment]
Convert to html and then do strip tags!

**Comment by theskumar** [comment]
But doesn't help with `Objective` and `Description`. We can ask for the `brief_description` explicitly. Thoughts?

**Comment by sivaa** [comment]
+1 for separate field(Objective or Summary) with ~200 chars maximum without mark down support.

**Comment by theskumar** [comment]
Having a summary as a char limited field also helps in populating a neat `<meta>` for description that will be used by google, facebook, etc.

**Comment by kracekumar** [comment]
-1 for asking user to enter one more form field. Convert markdown to html
or strip tags or use html2text to populate.

On Sun, Feb 8, 2015 at 10:21 PM, Saurabh Kumar <notifications@github.com>
wrote:

> Having a summary as a char limited field also helps in populating a neat
> <meta> for description that will be used by google, facebook, etc.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pythonindia/junction/issues/140#issuecomment-73419138>
> .
>



-- 
Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521

**Comment by theskumar** [comment]
I've added striping of markdown syntax in #148. :point_up: works by converting to html and then using built in `striptag` template filter. 

@sivaa you can review and close this PR.

**Comment by theskumar** [comment]
Refer to #149, what if just remove the description field. Going through the list of pyBelgaum junction... it didn't made any sense to keep it.

**Comment by theskumar** [comment]
not required as 'description' is removed from the proposal list. see #149
