### ISSUE TITLE
Proposal Detail - Reviewer Section is not working

### ISSUE THREAD

**Issue by sivaa** [pythonindia/junction#143]
The user with reviewer is not able to perform any actions on this tab.

![image](https://cloud.githubusercontent.com/assets/2163422/6152490/98f7b678-b243-11e4-9428-e5d5db865eca.png)

**Comment by theskumar** [comment]
@sivaa if this is fixed, can we close this issue?

**Comment by sivaa** [comment]
@theskumar Yep.
