### ISSUE TITLE
Show content upload status on proposal list page.

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/junction#145]
On proposal listing page we need to display if proposal has content link update.
In case content is not updated show them in different color.
If possible add functionality where reviewer can send reminder to submitter that content is not uploaded yet.

**Comment by theskumar** [comment]
Is it for tracking if content link is provided by the proposer or not, or something. 

If the we just want to track yes/no, then the implementation is just matter of checkin the `content_link` for emptyness and displaying the indicative UI, else i'm not sure of a tracking intermediate state of the content link.

**Comment by vnbang2003** [comment]
We need to check if content has some value so reviewer and other can go to particular link and read proposal.

**Comment by theskumar** [comment]
Thanks. I think that make sense. Do we want it from everyone or just for the reviewers?

**Comment by vnbang2003** [comment]
Everyone is fine.

**Comment by kracekumar** [comment]
If the content links are missing just show content links are missing as a
message in the top only to reviewers.

On Thu, Mar 5, 2015 at 1:13 PM, Vijay <notifications@github.com> wrote:

> Everyone is fine.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pythonindia/junction/issues/145#issuecomment-77320234>
> .
>



-- 
Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521

**Comment by vnbang2003** [comment]
I don't see harm in show to all . Any particular reason why only for reviewers ?

**Comment by kracekumar** [comment]
Viewer can't take any action with the message. Normally viewers want to
read the description, who the author is and links. Content url present or
not doesn't make any difference before conference,
it only makes sense after the conference is over.

On Thu, Mar 5, 2015 at 1:24 PM, Vijay <notifications@github.com> wrote:

> I don't see harm in show to all . Any particular reason why only for
> reviewers ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pythonindia/junction/issues/145#issuecomment-77321298>
> .
>



-- 
Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521

**Comment by sivaa** [comment]
How about Proposal Completeness Progress bar?

**Comment by kracekumar** [comment]
What are you trying to achieve by having this ? Whom it will help ?

On Thu, Mar 5, 2015 at 1:49 PM, Sivasubramaniam Arunachalam <
notifications@github.com> wrote:

> How about Proposal Completeness Progress bar?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pythonindia/junction/issues/145#issuecomment-77323844>
> .
>



-- 
Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521

**Comment by kracekumar** [comment]
If you guys feel it is ok to have it, please go ahead

On Thu, Mar 5, 2015 at 1:56 PM, Kracekumar Ramaraju <me@kracekumar.com>
wrote:

> What are you trying to achieve by having this ? Whom it will help ?
>
> On Thu, Mar 5, 2015 at 1:49 PM, Sivasubramaniam Arunachalam <
> notifications@github.com> wrote:
>
>> How about Proposal Completeness Progress bar?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/pythonindia/junction/issues/145#issuecomment-77323844>
>> .
>>
>
>
>
> --
> Regards
> Kracekumar Ramaraju
> http://kracekumar.com
> +91 85530 29521
>



-- 
Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521

**Comment by sivaa** [comment]
Some use cases from my side. @vnbang2003 can add more.
- If the proposal is not complete(i.e. No content/description/pre-requistes/speaker-info) means, there is no point for the reviewer or normal user to open that proposal(till it is updated).

**Comment by vnbang2003** [comment]
@sivaa I even had same point.

**Comment by kracekumar** [comment]
It doesn't make sense to submit a proposal without description, there
should be constraints in form and model to avoid this.
We also have draft option also, where proposer can avoid viewers to see
till the work is complete.

The only problem I am seeing is duplication of code and constraints at
various layers.


On Thu, Mar 5, 2015 at 5:24 PM, Vijay <notifications@github.com> wrote:

> @sivaa <https://github.com/sivaa> I even had same point.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pythonindia/junction/issues/145#issuecomment-77351653>
> .
>



-- 
Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521

**Comment by sivaa** [comment]
@kracekumar The constraints are already in place. I meant the scenarios like <TO BE UPDATED SOON>. 
Overall, how it needs to be implemented is still in pre-mature state. Its a nice to have, low priority feature.

**Comment by kracekumar** [comment]
No, default value for description is empty string,
https://github.com/pythonindia/junction/blob/master/junction/proposals/models.py#L75
.

On Thu, Mar 5, 2015 at 5:58 PM, Sivasubramaniam Arunachalam <
notifications@github.com> wrote:

> @kracekumar <https://github.com/kracekumar> The constraints are already
> in place. I meant the scenarios like .
> Overall, how it needs to be implemented is still in pre-mature state. Its
> a nice to have, low priority feature.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pythonindia/junction/issues/145#issuecomment-77355647>
> .
>



-- 
Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521

**Comment by kracekumar** [comment]
It makes sense to have indications for reviewers.

On Thu, Mar 5, 2015 at 5:49 PM, Kracekumar Ramaraju <me@kracekumar.com>
wrote:

> It doesn't make sense to submit a proposal without description, there
> should be constraints in form and model to avoid this.
> We also have draft option also, where proposer can avoid viewers to see
> till the work is complete.
>
> The only problem I am seeing is duplication of code and constraints at
> various layers.
>
>
> On Thu, Mar 5, 2015 at 5:24 PM, Vijay <notifications@github.com> wrote:
>
>> @sivaa <https://github.com/sivaa> I even had same point.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/pythonindia/junction/issues/145#issuecomment-77351653>
>> .
>>
>
>
>
> --
> Regards
> Kracekumar Ramaraju
> http://kracekumar.com
> +91 85530 29521
>



-- 
Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521

**Comment by vnbang2003** [comment]
I think let agree to show some indicator that content is not upload.
Let's make it visible to every one.

**Comment by kracekumar** [comment]
While loading the page in reviewers dashboard (`to_review view`), if the proposer has linked the contents in `Content URLs` display `link icon` in the proposal div along with tags `Talks`, `Web Developments` tags. 

#### Simple mockup
![screen shot 2015-07-05 at 2 46 38 pm](https://cloud.githubusercontent.com/assets/311929/8511071/c9dec158-2324-11e5-8fa5-dcbc0ce809a2.png)

Fontawesome link: https://fortawesome.github.io/Font-Awesome/icon/external-link/
Tooltip will "Content URL available"

Clicking on the link icon should take to the proposal detail page. 

### Bonus

We can also extract the link from the content url section and add href to the link. Clicking on it will open the link url in new page. If there are more than one url, we can link first one.

CSS can be copied from "Left review comment" icon in the same page.

**Comment by vnbang2003** [comment]
This sounds good to me.

**Comment by hTrap** [comment]
Please review https://github.com/pythonindia/junction/pull/311 for the above issue
