### ISSUE TITLE
Links not showing up as links on proposal page

### ISSUE THREAD

**Issue by pythonhacker** [pythonindia/junction#146]
E.g: http://junction.pybelgaum.org/pybelgaum/proposals/build-restful-web-services-with-pecan-and-wsme/ . Look under __Content URLs__ .

Not sure if this is a problem with the system or with the wrong markdown the submitter used. 

If this is a duplicate issue, pls. ignore.

**Comment by theskumar** [comment]
This was due to difference in preview compiler (JS based) and actual python markdown convertor.

Adding in autolinking extension to markdown compiler to fix this.
