### ISSUE TITLE
UI: remove 'description' from page proposals list

### ISSUE THREAD

**Issue by theskumar** [pythonindia/junction#149]
The description of the proposals on the list page makes the UI cluttered without much of the benefit. The description field is markdown sensitive, so conversion of markdown -> text can have weird output like (ref: #140, #148)

For 
```
## Goals

- learn basics of python
- hands on tutorial
```
output will be `Goals learn basics of python hands on tutorial`.

![a](https://www.dropbox.com/s/217qn4khqbdsc3f/Screenshot%202015-02-14%2009.43.55.png?dl=1)

vs

![b](https://www.dropbox.com/s/v4tvz94qs6ih53n/Screenshot%202015-02-14%2009.48.39.png?dl=1)

@sivaa @kracekumar @mudassir0909 thoughts?

**Comment by sivaa** [comment]
+1 for removing(Sine we are not providing object field too).

**Comment by mudassir0909** [comment]
I'd say let's not display description in the list. If we really need to display description we can display an icon which displays the description on hover http://getbootstrap.com/javascript/#popovers 

I can submit a PR now for that

**Comment by mudassir0909** [comment]
Something like this

![screen shot 2015-02-14 at 9 59 06 pm](https://cloud.githubusercontent.com/assets/1861842/6200228/af072c3e-b494-11e4-9f0a-6a7dd2fea021.png)

**Comment by sivaa** [comment]
@mudassir0909 +1

**Comment by theskumar** [comment]
@mudassir0909 @sivaa sounds good to me. Let's remove the description. The popover can be delayed, would be nice to have. :+1:

**Comment by sivaa** [comment]
@theskumar Yep. We can remove it for this issue. We can create a separate issue for pop-over.
