### ISSUE TITLE
Proposal List - Display the status of the proposal

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/junction#150]
We need to display the status of the proposal in list page to understand the status of the talk.
If possible provide filter which will help user to see easily talk with different status.

**Comment by theskumar** [comment]
Question: Do we want this for everyone or just for the reviewer?

We can have along side the different `tags` displayed in proposal list. Filtered by clicking on the link.

**Comment by vnbang2003** [comment]
I think it's fine to show to all.
if you see pybelgaum conference  we are not able to understand confirmed talk at all.

http://junction.pybelgaum.org/pybelgaum/proposals/?proposal_type=3

**Comment by theskumar** [comment]
Understood. I'll take a stab at it.

**Comment by vnbang2003** [comment]
We show the display of selected status in different section which should close this issue.
closing the ticket. reopen if i missed any point.
