### ISSUE TITLE
make project name configurable

### ISSUE THREAD

**Issue by ChillarAnand** [pythonindia/junction#157]
right now in email messages & other places we are using project name as `junction`, instead we have to set in settings & get from there

**Comment by bhanuvrat** [comment]
@ChillarAnand 
Has this issue been fixed? I couldn't locate a template which has 'junction hardcoded into it' could you share a screen shot of the mail you recieved?

**Comment by ChillarAnand** [comment]
not yet. 

couple of locations:

[base template](https://github.com/pythonindia/junction/blob/master/junction/templates/base.html#L89)
[email subject](https://github.com/pythonindia/junction/blob/master/settings/common.py#L92)

i am not sure if there are any other places to change.

**Comment by bhanuvrat** [comment]
@ChillarAnand oh okay.
I was looking at the subject of the mail.

**Comment by bhanuvrat** [comment]
@ChillarAnand there is already a site_name variable and a context processor which injects it in templates. Shall submit a push request soon.

**Comment by bhanuvrat** [comment]
check out #168
