### ISSUE TITLE
Add tweet on each proposal submission

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/junction#159]
Once new proposal submission,  we can add tweet in conference twitter account.
This will help people to track what happening on submission.

**Comment by vnbang2003** [comment]
@sivaa How time much do you think we need to get this feature ? I was thinking to get it by PyCon India 2015

**Comment by sivaa** [comment]
@vnbang2003 It is in the list of top 4 items to be implemented. We will get it closed soon.

**Comment by vnbang2003** [comment]
@kracekumar @sivaa  We will be going tomorrow . Is it deployed in production ?

**Comment by kracekumar** [comment]
Just merged this. We will deploy.

On Fri, Mar 6, 2015 at 4:01 PM, Vijay <notifications@github.com> wrote:

> @kracekumar <https://github.com/kracekumar> @sivaa
> <https://github.com/sivaa> We will be going tomorrow . Is it deployed in
> production ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pythonindia/junction/issues/159#issuecomment-77538267>
> .
>



-- 
Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521
