### ISSUE TITLE
Up Vote count and Comments counts are wrong in the smaller/mobile screens

### ISSUE THREAD

**Issue by sivaa** [pythonindia/junction#161]
It looks like both are interchanged.
![image](https://cloud.githubusercontent.com/assets/2163422/6316703/0a67d6d2-ba58-11e4-9251-8306b9674745.png)

**Comment by theskumar** [comment]
They seems to look fine to me.
![adsf](https://www.dropbox.com/s/11dphkca6lnmccs/Screenshot%202015-03-28%2009.09.58.png?dl=1)

and 

![a](https://www.dropbox.com/s/yt92wi3vxqpt5pw/Screenshot%202015-03-28%2009.11.00.png?dl=1)

votes = 14, comment=2

**Comment by ChillarAnand** [comment]
it works for me too

**Comment by theskumar** [comment]
ok. closing this. @sivaa please reopen if you need.
