### ISSUE TITLE
Add custom admin action to proposals

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/junction#162]
Define a custom admin action for proposal objects which trigger emails for
1) request to upload content.
2) Talk status change email on state change.

**Comment by vnbang2003** [comment]
@ChillarAnand  update on this ?

**Comment by ChillarAnand** [comment]
@vnbang2003 will do it in couple of days

**Comment by ChillarAnand** [comment]
Admin will be accessible to only organizing team. May be we should add a button in proposal detail page, which will be accessible to reviewers to send mails for content upload? 

@vnbang2003 @kracekumar Thoughts?

**Comment by vnbang2003** [comment]
Am fine either way .More important is we need this feature asap.
If required we can move button and make it custom admin action later if we don't find it appropriate
