### ISSUE TITLE
Breadcrumb issue

### ISSUE THREAD

**Issue by kracekumar** [pythonindia/junction#164]
When `junction` is deployed on `foo.org/junction` bread crumb doesn't work. For example clicking on `Home` takes to `foo.org` rather than `foo.org/junction`.

**Comment by theskumar** [comment]
@kracekumar it's because the junction is designed to run under a fully qualified domain and not path based top-level. If it's not absolutely required, to have sub-path like `/junction/` I would prefer to deploy at it under a sub-domain.

**Comment by kracekumar** [comment]
@theskumar Even I could deploy that but `in.pycon.org` is sub domain on `pycon.org`. There is no choice. So how to proceed ?

**Comment by theskumar** [comment]
We have to get rid of `django.contrib.sites` and either use `django_sites` or use a hard coded `SITE_URL=https://in.pycon.org/junction/` like it's being done for wordpress and make use of it everywhere.

**Comment by theskumar** [comment]
`SITE_URL` context variable seems  be quickest best solution with `{{ SITE_INFO.site_url }}{% url 'homepage' %}` replaced everywhere. 

PS: This need to be maintained and checked for each PRs in future.

**Comment by theskumar** [comment]
You also need to appropriately override the `STATIC_URL` and `MEDIA_URL`

**Comment by kracekumar** [comment]
@vigneshsarma Any thoughts on it ?

**Comment by theskumar** [comment]
I'll also trying to override the `django.templates.defaulttags.url` for it to support `SITE_URL` it's present to we don't have to make any change to `{% url ...` in templates.

**Comment by kracekumar** [comment]
sure.

On Tue, Feb 24, 2015 at 10:52 AM, Saurabh Kumar <notifications@github.com>
wrote:

> I'll also trying to override the django.templates.defaulttags.url for it
> to support SITE_URL it's present to we don't have to make any change to {%
> url ... in templates.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pythonindia/junction/issues/164#issuecomment-75701487>
> .
>



-- 
Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521

**Comment by theskumar** [comment]
@kracekumar i've given it a try at https://github.com/pythonindia/junction/pull/167

It patches the `url` tag to make use of `SITE_URL`, which i think is fine.
I have also patched the `django.core.urlresolvers.reverse` to be on the safe side, I see it being used to models to get absolute urls. 

You can set SITE_URL to be fully qualified url like `http://in.pycon.org/junction` or just a path `/junction`
setting it to `/junction` is preferable at it keeps the current semantics of url tag and reverse making patch like `/hello-world` to `/junction/hello-world`.

**Comment by kracekumar** [comment]
Sure. Will merge and if there are any issues will open one.
