### ISSUE TITLE
sample dataset

### ISSUE THREAD

**Issue by bhanuvrat** [pythonindia/junction#169]
The fixtures that come with the repo don't contain sample proposals and comments.
Some data would be helpful in understanding issues and also for testing whether things are getting screwed. How are you managing without it?

**Comment by kracekumar** [comment]
+1 for enhancing it.

On Tue, Feb 24, 2015 at 11:08 PM, Anuvrat Parashar <notifications@github.com
> wrote:

> The fixtures that come with the repo don't contain sample proposals and
> comments.
> Some data would be helpful in understanding issues and also for testing
> whether things are getting screwed. How are you managing without it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pythonindia/junction/issues/169>.
>



-- 
Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521

**Comment by ChillarAnand** [comment]
@bhanuvrat are you working on this?

**Comment by bhanuvrat** [comment]
@ChillarAnand no I haven't been.
I was hoping to get a dump of the production database for pybelgaum and use its subset as sample data. What say?

**Comment by kracekumar** [comment]
Not really, we can't share the data.

On Tue, Mar 17, 2015 at 12:00 AM, Anuvrat Parashar <notifications@github.com
> wrote:

> @ChillarAnand <https://github.com/ChillarAnand> no I haven't been.
> I was hoping to get a dump of the production database for pybelgaum and
> use its subset as sample data. What say?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pythonindia/junction/issues/169#issuecomment-81856254>
> .
>



-- 
Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521

**Comment by ChillarAnand** [comment]
we are using djagno-sampledatahelper to generate sample data. it gives fine control over the sample data that is loaded into db. but it has couple of issues.

1. if our models/schema changes, we need to modify code which creates sample data.
2. whenver a new model is added, we have to write code to generate sample data.

instead we can use [django-autofixture](https://github.com/gregmuellegger/django-autofixture). 

    python manage.py loadtestdata proposals.ProposalComment:10 proposals.Proposal:20

this generates 10 comments & 20  proposals. with this we don't have to worry about above issues but we wont have fine control over the data loaded into db. 

@kracekumar @sivaa @theskumar any suggestions about this?

**Comment by theskumar** [comment]
@ChillarAnand I'm just exploring a couple of options we can go with.

1. How about a a mix of both. I won't mine a simple `.sh` script to do it.
2. Since the `sampledatahepler` provides auto fixtures too, how about just using the same as mix in the sample_data management command. Again a hybrid approach.

That said, I feel that if we are conscious enough, we can always point out to update the sample_data management command whenever there is a model change in a PR.

**Comment by kracekumar** [comment]
Anand, Saurabh both the ideas are welcome. It is not possible to replicate
100% of cases.
If we are able to cover creating conference, proposals, reviewers, comments
most of the cases, we're good enough.



On Tue, Mar 17, 2015 at 4:14 PM, Saurabh Kumar <notifications@github.com>
wrote:

> @ChillarAnand <https://github.com/ChillarAnand> I'm just exploring a
> couple of options we can go with.
>
>    1. How about a a mix of both. I won't mine a simple .sh script to do
>    it.
>    2. Since the sampledatahepler provides auto fixtures too, how about
>    just using the same as mix in the sample_data management command. Again a
>    hybrid approach.
>
> That said, I feel that if we are conscious enough, we can always point out
> to update the sample_data management command whenever there is a model
> change in a PR.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pythonindia/junction/issues/169#issuecomment-82266839>
> .
>



-- 
Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521

**Comment by kracekumar** [comment]
@ChillarAnand Do you need any specific inputs ? I think we can also mandate adding sample data as part of pull requests for all new features/bugs.
