### ISSUE TITLE
Rest api for junction 

### ISSUE THREAD

**Issue by ChillarAnand** [pythonindia/junction#171]
We need to create rest api for junction so that android app or any other service can use it.

**Comment by bhanuvrat** [comment]
+1

**Comment by kracekumar** [comment]
We need to have more writeup about what sort of data we need to give out. We will use this issue to track that.

**Comment by kracekumar** [comment]
As of now we need api for `schedule and feedback`. 

Dummy Schedule API: https://github.com/pythonindia/junction/blob/master/junction/templates/dummy_schedule.json
Schedule API issue: https://github.com/pythonindia/junction/issues/225
Feedback API issue: https://github.com/pythonindia/junction/issues/19

Spoke to people offline, everyone is happy to use `DRF`. If there are second opinion please share.

**Comment by kracekumar** [comment]
We already have working API for mobile development. New endpoint entry will have separate issue.
