### ISSUE TITLE
Create Proposal - UI Enhancements

### ISSUE THREAD

**Issue by sivaa** [pythonindia/junction#177]
This center alignment doesn't look cool. It should be left aligned and the help text should be right aligned.

![image](https://cloud.githubusercontent.com/assets/2163422/6541305/198022aa-c4ee-11e4-9b56-b6ae5d1597fe.png)

**Comment by theskumar** [comment]
This seems have been resolved in lastest build and it just need a deployment.

Reference:
![a](https://www.dropbox.com/s/zr5ngpdjdvhfbsu/Screenshot%202015-03-28%2010.24.09.png?dl=1)

Closing this, please reopen if required.
