### ISSUE TITLE
Siging up for junction shows that the "PyBelgaum" is requesting for permission

### ISSUE THREAD

**Issue by shrayasr** [pythonindia/junction#186]
Tried signing up to InPycon junction today with my Google account and it shows that "PyBelgaum" would like to access my details

Screenshot: 
![screenshot 2015-03-19 11 32 01](https://cloud.githubusercontent.com/assets/240368/6726280/6fdfcab4-ce3b-11e4-9c97-f629e93ac5c5.png)

Bug caught by @raghothams

**Comment by kracekumar** [comment]
It is fixed now. Thanks @shrayasr @raghothams.

**Comment by shrayasr** [comment]
:+1: :)

**Comment by raghothams** [comment]
👍
