### ISSUE TITLE
Login link in Comments section on [PyCon 2015] Proposal description page redirects to 404 - Page not found

### ISSUE THREAD

**Issue by ProProgrammer** [pythonindia/junction#187]
Prerequisite: User should not be already logged into https://in.pycon.org/cfp/pycon-india-2015/proposals/
Proposals page: https://in.pycon.org/cfp/pycon-india-2015/proposals/

The proposal description page can be reached by clicking on titles of any of the proposals (Under "List of Proposals" section)

When clicking on "Login" link under Comments section on the proposal description page, it redirects to "404 Not Found".

Screenshot:
![pycon_404_login_link_proposal_description_page](https://cloud.githubusercontent.com/assets/3947424/6775755/d5afbb7e-d15b-11e4-9702-102a0fb8d99b.png)

**Comment by kracekumar** [comment]
Fixed in https://github.com/pythonindia/junction/commit/a66259f42f1d93fd4f26164985941f7b325d0bea. Can you try now ?

**Comment by ProProgrammer** [comment]
Working fine :+1:
