### ISSUE TITLE
Feedback Collection

### ISSUE THREAD

**Issue by sivaa** [pythonindia/junction#19]

**Comment by vnbang2003** [comment]
@kracekumar  Can we also define more details here so we soon get this feature up.

**Comment by kracekumar** [comment]
I will be updating all the details what is required this week.

On Wed, Jul 1, 2015 at 10:02 AM, Vijay <notifications@github.com> wrote:

> @kracekumar <https://github.com/kracekumar> Can we also define more
> details here so we soon get this feature up.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pythonindia/junction/issues/19#issuecomment-117432103>
> .
>



-- 
Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521

**Comment by kracekumar** [comment]
`Feedback` will be submitted anonymously but all feedback data will have `UUID` as discussed in https://github.com/pythonindia/junction/issues/298.

We need to have flexible feedback objects. Every section should have feedback template. `Talks and Workshops` will different data points. As of now our paper based feedback form has same data like `How was the content ? +1, 0, -1, How was the presentation ? +1, 0, -1? and some text to give feedback`.

We can follow the similar structure and add or reduce the number of questions. Feedback creator should be allowed to create `question`  and `question type (multiple choice or text)` similar to Google Forms (look for some Django packages) and once done with it, organizer should associate the questions with `proposal type`.

### Feedback api

In initial version we will support `read, write` for a feedback and not edit. When a mobile client requests for feedback data (`GET` request) on `api/v1/feedback/<session_id>/` the server will look for `session_type` and return feedback data to client.

Client will `post` the data back to same url with `uuid` and user submitted data. We will store the feedback data only if the uuid is verified in our database.

Before starting the work we can come up with up API structure.

**Comment by kracekumar** [comment]
This feature is available in master branch.
