### ISSUE TITLE
Add steps to install virtualenv

### ISSUE THREAD

**Issue by Aayush-Kasurde** [pythonindia/junction#194]
It is better to write installation steps for virtualenv in installation guidelines.

**Comment by ProProgrammer** [comment]
@kracekumar with regards to installation steps for virtualenv, please review this and let me know if I should go ahead and create a pull request.
https://github.com/pythonindia/junction/compare/master...ProProgrammer:patch-2?name=patch-2&short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8

Thanks

**Comment by theskumar** [comment]
@ProProgrammer thanks for this. 80% use case for this a new comer to this project. With this in context, the it would be wise to advise not to add the virtualenv directory accidentally being added to version control. There are couple of approach we can go with:

1. Using virtualenvwrapper.
2. Advising on using a consistent name like `venv` for virtualenv folder which can be added to global gitignore at `~/.gitignore` 

Here's my take on using virtualenv efficiently (if not using virtualenv wrapper): https://saurabh-kumar.com/blog/virtualenv-vs-virtualenvwrapper.html

**Comment by Aayush-Kasurde** [comment]
@theskumar sounds good to me. @ProProgrammer refer [fedora-infra/anitya] (https://github.com/fedora-infra/anitya/blob/master/README.rst) for virtualenv example.

**Comment by kracekumar** [comment]
It is not worth adding virtualenv installation steps.

**Comment by theskumar** [comment]
I'm also in favour of not adding it, a [mighty] url to some reference resource is enough. The current one is good enough.

PS: closing this issue for the sake of sanity.
