### ISSUE TITLE
Release 0.3.0

### ISSUE THREAD

**Issue by theskumar** [pythonindia/junction#196]
__Goals__

- Better testing

Changeset: https://github.com/pythonindia/junction/compare/0.2.0...master

----

__Features__

- [x] conference moderators can be added per conference using a `conference_moderator` management command.
- [x] Improved conference admin.
- [x] Basic REST API for accessing conference details and proposals.
- [x] REST API to submit feedback for a talk/workshop.
- [x] UI updates  

__Fixes__
- [x]  fix the tag filtering for all the proposal sections inside proposal list (#170)
- [x] Update proposal detail styling (#207)

**Comment by theskumar** [comment]
@kracekumar We should make a new release, as a lot of things have been updated/add in the master since this release. There are almost 450+ commits.

Do we need to do any preliminary checks before this release?

**Comment by kracekumar** [comment]
@theskumar Master branch is up to date. It's good to make a release.
