### ISSUE TITLE
Show reviewers tab in proposal detail page for reviewers in that section 

### ISSUE THREAD

**Issue by kracekumar** [pythonindia/junction#197]
All the reviewers can see the `reviewers` comments in proposal detail page. Reviewers who belong to the section should only see the `comments/tab`.

**Comment by vnbang2003** [comment]
I think our present schema doesn't allows us to map section to reviewers.
Is it only UI fix ?

**Comment by kracekumar** [comment]
We have a model for it,
https://github.com/pythonindia/junction/blob/master/junction/proposals/models.py#L36
.

On Thu, Apr 2, 2015 at 2:35 PM, Vijay <notifications@github.com> wrote:

> I think our present schema doesn't allows us to map section to reviewers.
> Is it only UI fix ?
>
> —
> Reply to this email directly or view it on GitHub.
>



-- 
Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521
