### ISSUE TITLE
inconsistent urls.py filenames

### ISSUE THREAD

**Issue by bhanuvrat** [pythonindia/junction#199]
Is there a specific reason why the urls.py_s of the application do not follow a consistent pattern? I mean there is `junction/urls.py` then there is `junction/pages/urls.py`, followed by `junction/comments/comments_urls.py` and `junction/proposals/proposals_urls.py`. 

is the pages app not following the convention, or are proposals and comments out of sync?
please advice.

**Comment by kracekumar** [comment]
It has been individual's preference, other than that I don't find any real
reason.

On Sun, Apr 5, 2015 at 6:22 PM, Anuvrat Parashar <notifications@github.com>
wrote:

> Is there a specific reason why the urls.py_s of the application do not
> follow a consistent pattern? I mean there is junction/urls.py then there
> is junction/pages/urls.py', followed byjunction/comments/comments_urls.py
> andjunction/proposals/proposals_urls.py`.
>
> is the pages app not following the convention, or are proposals and
> comments out of sync?
> please advice.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pythonindia/junction/issues/199>.
>



-- 
Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521

**Comment by theskumar** [comment]
like krace said it's more of a individual preference. And that said, we shouldn't have any issue changing them to be more consistent and community acceptable.

**Comment by theSage21** [comment]
I will do this bit.

**Comment by theSage21** [comment]
@bhanuvrat Close the issue? PR #238 is merged
