### ISSUE TITLE
License

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/junction#210]
We need to come up with license type for junction.

**Comment by kracekumar** [comment]
https://github.com/pythonindia/junction/blob/master/LICENSE

On Sun, Apr 19, 2015 at 7:56 PM, Vijay <notifications@github.com> wrote:

> We need to come up with license type for junction.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pythonindia/junction/issues/210>.
>



-- 
Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521
