### ISSUE TITLE
Bug in Proposals To Be Reviewed Section

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/junction#216]
Looks like the condition check for Proposal to be review section is incorrect.
https://in.pycon.org/cfp/pycon-india-2015/proposals/
For Example: 
        For Proposal "Test Driven Development with Ansible"  there is no review comments provided but it's not listed in "Proposals To Be Reviewed" section.
Let me know if my understand is incorrect.

**Comment by kracekumar** [comment]
Yes this is a bug. Reviewers comments aren't displayed in the section. @ChillarAnand Can you have a look ?

**Comment by ChillarAnand** [comment]
@kracekumar  @vnbang2003  fixed it.

**Comment by kracekumar** [comment]
@vnbang2003 Please check this, also the sections you're part of review will be displayed not all proposals.

**Comment by vnbang2003** [comment]
@ChillarAnand @kracekumar Thanks for quick fix. Do you guys think moving to separate tab will be good idea to make is user friendly ?

**Comment by kracekumar** [comment]
+1 for separate tab.

On Tue, Apr 28, 2015 at 10:47 AM, Vijay <notifications@github.com> wrote:

> @ChillarAnand <https://github.com/ChillarAnand> @kracekumar
> <https://github.com/kracekumar> Thanks for quick fix. Do you guys think
> moving to separate tab will be good idea to make is user friendly ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pythonindia/junction/issues/216#issuecomment-96912654>
> .
>



-- 
Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521

**Comment by vnbang2003** [comment]
Lets open new Issue so we don't forget about this.

**Comment by vnbang2003** [comment]
This is not fixed yet. Please look at 
https://in.pycon.org/cfp/pycon-india-2015/proposals/distributed-programming-with-celery/
We need to fix it.

**Comment by vnbang2003** [comment]
Even this :https://in.pycon.org/cfp/pycon-india-2015/proposals/getting-started-with-vtk-in-python-for-scientific-visualization/

**Comment by ChillarAnand** [comment]
> For Proposal "Test Driven Development with Ansible" there is no review comments provided but it's not listed in "Proposals To Be Reviewed" section.

 If logged in user is the reviewer of that section then only it will be displayed in review section.

> Reviewers comments aren't displayed in the section.

reviewer comments will be shown only to section reviewers. 

@vnbang2003  @kracekumar  unable to reproduce locally.  implementation ( [[1]](https://github.com/pythonindia/junction/blob/master/junction/proposals/views.py#L61-L67) [[2]](https://github.com/pythonindia/junction/blob/master/junction/proposals/views.py#L156) ) looks okay?

**Comment by vnbang2003** [comment]
@kracekumar  Are you able to see bug  in PyCon India CFP ?  I still see it as bug in CFP 2015

**Comment by vnbang2003** [comment]
How about doing this
Add new proposal status - Review in progress
Once one of the reviewer put his comment we trigger a signal to change status from "Yet to be reviewed"  to "Review in progress".
This will provide us more consistency and simply query.

**Comment by vnbang2003** [comment]
@ChillarAnand Take a look at screen shot for reference on bug in prodution.
GIve you me user id in inpycon cfp i will added you to reviewers list  to show what's happening.

![Uploading Screen Shot 2015-05-12 at 10.11.17 AM.png…]()
![screen shot 2015-05-12 at 10 11 28 am](https://cloud.githubusercontent.com/assets/316253/7580261/4f2064b8-f88f-11e4-8e25-c592e85745a2.png)

**Comment by ChillarAnand** [comment]
@vnbang2003  userid: chillaranand

**Comment by vnbang2003** [comment]
Looks like intention of Proposal to be reviewed is to let user know that they have not reviewed but i can happen that other reviewers would have reviewed . Hence closing the bug.
