### ISSUE TITLE
Blog Application

### ISSUE THREAD

**Issue by sivaa** [pythonindia/junction#22]

**Comment by theskumar** [comment]
Is the blog application conference wise or just for the junction project itself?

If the blog is for junction project, can we have it as an independent application using third bloggin solution, maybe tumblr or svbtle. Just a random thought.

**Comment by sivaa** [comment]
@theskumar Currently, this project is being implemented only for managing proposals. In near future, we might think about displaying the static data related to the entire conference. We can generate these static pages using some populated data from DB(Ex: Sponsorships). At that point we might need a blogging application.

@vnbang2003  @kracekumar any thoughts?

**Comment by vnbang2003** [comment]
Is junction gone support dynamic subscription of sponsorship and other things in future ?
If not we might not need blog ?

**Comment by vnbang2003** [comment]
@vigneshsarma @kracekumar As you guys are working on it. Please close one app is live

**Comment by kracekumar** [comment]
Closing this issue, since it is not of any priority right now.
