### ISSUE TITLE
Reviewers should be able to view/post reviews for other sections

### ISSUE THREAD

**Issue by punchagan** [pythonindia/junction#221]
Currently, reviewers are only allowed to post reviews for sections they are assigned as reviewers.  They are not allowed to view/post new reviews on sections for which they are not reviewers. 

At the very least, all review comments should be visible.  This helps reviewers see what sort of feedback other reviewers are providing, and helps them incorporate good stuff into their own feedback. 

A reviewer may not be an expert in a section but may want to provide some generic feedback regarding a proposal.  This could be done in an ordinary comment (instead of a reviewer comment), though. 

@vanishan tells me via email that this is by design, to prevent spamming the reviewers.  This problem, if at all it is one, should be fixed by allowing reviewers to turn on/off email rather than not letting them view comments by other reviewers.

**Comment by pythonhacker** [comment]
I am joining this issue. All reviewers should be able to see other review comments whether they are able to write or not. In other words, read access to all reviews, write access to only their sections should be the design.

**Comment by ChillarAnand** [comment]
+1, since we are hiding reviewer names in comment section, providing read access to comments for all reviewers shouldn't be an issue.

**Comment by vnbang2003** [comment]
@kracekumar @ChillarAnand  Can we hide submit button in reviewer section to get this feature live?
emails logic can remain same.

**Comment by ChillarAnand** [comment]
@vnbang2003 @kracekumar  should we hide `add comment` button in reviewers comments for other sections?

**Comment by vnbang2003** [comment]
I think that easiest fix . @kracekumar what do you say ?

**Comment by kracekumar** [comment]
Yes, that looks easiest fix. @ChillarAnand Go ahead with it.
