### ISSUE TITLE
[Feature] Provide reviewers-only comment/discussion section

### ISSUE THREAD

**Issue by pythonhacker** [pythonindia/junction#222]
Vanitha had asked suggestion about an ML for reviewers. I am verbatim copying my email response to her on that.

"""
I am a bit against an ML as you know it takes some amount of self
discipline to summarize your thoughts and post on MLs to have a good,
directed and positive discussion. We can see inpycon as an example of
this practiced both in the right and wrong.

An ML for reviewers has a high probability to go off in different
directions and scatter the energy than focus it - with the limited
time we have on reviewing it may not be the right tool.

Rather than an ML I suggest to build a workflow in the system
(junction) where reviewers can talk with each other about a talk
without the proposer seeing it. This should be specific for each talk
(like the "reviewers comments" tab  right now). Thus discussions would
be focused on a talk rather than all over the place - which can happen
in an ML.
"""

This issue is filed to provide a workflow in the system where reviewers can discuss a talk without the proposer seeing it. This could be implemented as a third tab possibly called "Reviewer Talk" or "Reviewer discussion" in the current view.

**Comment by pythonhacker** [comment]
Note that this is partly inspired by the "Talk" section of Wikipedia articles which work pretty well.

**Comment by vnbang2003** [comment]
we can add new Reviewers only tab where all reviewers can comment and it will be displayed to all reviewers . Do we need emails to be triggered for all this conversation  ?

**Comment by theskumar** [comment]
+1 from my side. Emails with links would be helpful. Sent to all reviewers involved in the talk?

**Comment by pythonhacker** [comment]
More requirement specs here.

   1. This section should be RO for all reviewers and RW for the specific reviewers.
   2. Unlike the current anonymous reviews shared with proposers this should NOT be anonymous. I need to know who I am discussing with the nitty-gritties of a proposal for it to be effective. I suggest showing the handle of the reviewer if not the full name.
   3. Email notifications are good - like the current ones when someone adds a comment. 
   4. Possibly also a moderator role would be nice - this can be fixed for each section. Like userx is moderator for "Core Python" reviews so he automatically becomes moderator for such discussions. But this is a nice-to-have not immediate.
   5. Put a global max comments per reviewer limit for this section - just to make sure there are no wild arguments and flame throwing leading to no consensus. This forces the reviewer to be succinct and express his thoughts well per comment. Something like 10.

**Comment by vnbang2003** [comment]
Am looking into it .

**Comment by pythonhacker** [comment]
I can see this now in Junction, so isn't this done ? The issue should be closed now.

**Comment by kracekumar** [comment]
As of now it is visible for section reviewers. Let's say you're reviewer
for Core Python and not reviewer for Network Programming, the section won't
show up in latter. We're fixing that as well, then we will close the issue.



On Mon, Jun 1, 2015 at 12:27 PM, Anand B Pillai <notifications@github.com>
wrote:

> I can see this now in Junction, so isn't this done ? The issue should be
> closed now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pythonindia/junction/issues/222#issuecomment-107330030>
> .
>



-- 
Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521

**Comment by vnbang2003** [comment]
I will fix and send patch in next 2 days and close it.

**Comment by kracekumar** [comment]
@vnbang2003 We can close this right ?

**Comment by vnbang2003** [comment]
Below two point are not taken care.
Possibly also a moderator role would be nice - this can be fixed for each section. Like userx is moderator for "Core Python" reviews so he automatically becomes moderator for such discussions. But this is a nice-to-have not immediate.
Put a local (per proposal) max comments per reviewer limit for this section - just to make sure there are no wild arguments and flame throwing leading to no consensus. This forces the reviewer to be succinct and express his thoughts well per comment. Something like 10.

Will open separate issues for the them.
