### ISSUE TITLE
Dashboard page to show stats  of talk based on section, Level, proposal sections

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/junction#223]
We should add dashboard page which will show stats of talk in different way
1) Based on Talk
2) Based on Sections
3) Based on Proposals
4) Overall 
5) Reviewers Based 

This Grid will have count, reviewed and unreviewed column to make it more readable.
Once you click on number it should take to make CFP page with filtered.

I am working on it . Let me know we need to add more in this page.

**Comment by vnbang2003** [comment]
@kracekumar @sivaa @theskumar Let me know you feedback on this feature

**Comment by kracekumar** [comment]
I think, for initial version this looks good. I think this dashboard will
be used by Conference chair right ?

On Thu, May 7, 2015 at 10:18 PM, Vijay <notifications@github.com> wrote:

> @kracekumar <https://github.com/kracekumar> @sivaa
> <https://github.com/sivaa> @theskumar <https://github.com/theskumar> Let
> me know you feedback on this feature
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pythonindia/junction/issues/223#issuecomment-99935873>
> .
>



-- 
Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521

**Comment by vnbang2003** [comment]
Initial plan was for Conference Organizing team. Now i think it not harmful to make it publicly available.

**Comment by kracekumar** [comment]
I am not yet convinced to have this publicly available to everyone.

On Thu, May 7, 2015 at 10:22 PM, Vijay <notifications@github.com> wrote:

> Initial plan was for Conference Organizing team. Now i think it not
> harmful to make it publicly available.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pythonindia/junction/issues/223#issuecomment-99936939>
> .
>



-- 
Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521

**Comment by vnbang2003** [comment]
Every time user need to add group or permission by name organiser will be confusing.

**Comment by ChillarAnand** [comment]
if we are going to add datetime for proposals([#255](https://github.com/pythonindia/junction/issues/225)); we can inlcude timeline in dashboard, where proposals will be dipslayed with respect to time/audi?

**Comment by vnbang2003** [comment]
Have commited the code to master branch directly. It's need some UI work . Will do in next few days.
Will open issue to filter proposal page with reviewer based filter like proposal_type.

https://github.com/pythonindia/junction/commit/5ec5f6ecf58e7ab0547411c21efebb5dc1539886
![screen shot 2015-05-10 at 11 51 03 am](https://cloud.githubusercontent.com/assets/316253/7553255/fbb6b2e4-f70a-11e4-8ecd-54adc6a6ed8b.png)

**Comment by vnbang2003** [comment]
@kracekumar @ChillarAnand @sivaa @theskumar : Take a look and provide feedback on any changes.
