### ISSUE TITLE
Scheduling feature

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/junction#225]
It would be good to have datetime fields in proposal models so organizer or editoral panel can add date time and see the schedule page directly here instead of taking it offline working on excel sheet.
This page initial should be visible to only reviewers . Organizer or one of editorial team will have permission to make it public.

**Comment by vnbang2003** [comment]
Adding more details 
We can add datetime fields where admin can add value to this fields. Taking datetime value it should populate schedule page automatically.
Editoral Panel can provide feedback if they want few thing to change. 
@kracekumar Let me know if it make sense.

**Comment by vnbang2003** [comment]
@kracekumar @ChillarAnand Can you please provide details so we prepare ourself before schedule is gone come up.

**Comment by kracekumar** [comment]
I will provide the details in this weekend.

**Comment by kracekumar** [comment]
We have a dummy schedule api here `https://github.com/pythonindia/junction/blob/master/junction/templates/dummy_schedule.json`.

### Feature

Junction should support scheduling feature. We need to have UI to create schedule (drag and drop) and api for mobile client consumption.

Organizer should be able to create a venue with `Name, Google Map URL`. Venue consists of rooms. `Rooms` should have `name, floor, note`. `Note` can take details how to navigate.

Conference should have `name`, `timezone`, `start_datetime` and `end_datetime`. Organizer should be presented with list of selected proposals.

Organizer should create days of the conference and `start_datetime` and `end_datetime` and create slots like `10.00 AM to 10.45` associated with days. Once slots are created organizer can drag and drop the selected proposal to a time slot to a room. We call this as session. Session can be `talk, workshop, open space, break, lunch`. Session will have special flags called `is_break, is_lunch` which will be helpful for mobile clients.

### API

Consider the api schema as draft version `https://github.com/pythonindia/junction/blob/master/junction/templates/dummy_schedule.json`. As we progress the api can be fine tuned.

**Comment by kracekumar** [comment]
@vigneshsarma will working on to get api first and then go ahead with UI.

**Comment by kracekumar** [comment]
Scheduling is possible with Admin UI.
