### ISSUE TITLE
Nitpicking - Wrong source of comment in email

### ISSUE THREAD

**Issue by pythonhacker** [pythonindia/junction#227]
There is a new comment on "xxxxxxxxxx" by one of the reviewer.:

"Hi Reviewer I have ............ Thanks author"

Clearly the source of the comment is wrongly interpreted by junction. I think it always puts __reviewer__ even though the comment is sometimes from the __proposer__ .

Possibly an easy-fix and nice-to-have. Not urgent.

**Comment by theSage21** [comment]
@pythonhacker I will fix this but I cannot find an example where the flaw is seen. Loking at the code everything seems fine. Can you post a test case?

**Comment by pythonhacker** [comment]
See this email (screenshot) for example.
![screenshot-new comment on cyber intelligence using python - pyconindiacfp - letterbox - mozilla thunderbird](https://cloud.githubusercontent.com/assets/316177/7907617/2df06c0a-0859-11e5-9646-fdb39c0a2ae3.png)

This email is clearly from the __proposer__, not from the __reviewer__ . But the email says it is from the __reviewer__ .

**Comment by theSage21** [comment]
Close the issue? #275 fixes this.
