### ISSUE TITLE
distinct(*fields) is not available for all databases

### ISSUE THREAD

**Issue by ChillarAnand** [pythonindia/junction#233]
```
sections =  ProposalSectionReviewer.objects.filter(
            conference_reviewer__reviewer=request.user)\
        .distinct('proposal_section__id')
```

i am testing junction on sqlite db and it can't render dashboard view as sqlite cannot support `distinct(*fields)`

**Comment by vnbang2003** [comment]
We have used distinct to make sure even if reviewers my mistake is assigned to same section twice it doesn't show wrong numbers
To remove distinct we need to make sure add validation for ProposalSectionReviewer once we do this we can remove this distinct .
This bring me next question for discussion should we support sqlite db ?

**Comment by kracekumar** [comment]
Sqlite has lot of these problems, not worth worrying. Use postgres or mysql.

**Comment by vnbang2003** [comment]
@ChillarAnand  Do you agree with @kracekumar  comments. If yes we can close the issue

**Comment by ChillarAnand** [comment]
Note: distinct(*fields) works [__only on__ PostgreSQL](https://docs.djangoproject.com/en/dev/ref/models/querysets/#distinct)

@vnbang2003  @kracekumar  can we reformulate query?

```
sections = ProposalSectionReviewer.objects.filter(
             conference_reviewer__reviewer=request.user)\
        .distinct('proposal_section__id').values('proposal_section__id').distinct()
```

**Comment by vnbang2003** [comment]
If we add validation at the time of add reviewer to section we can remove distinct () till that point we need this. Please open bug  if required.
