### ISSUE TITLE
dashboard enhancements

### ISSUE THREAD

**Issue by ChillarAnand** [pythonindia/junction#235]
we can add more columns to the table so that reviewers can have more clarity.
1. drafts
2. public (reviwers comment=0)
3. reviewing (reviewer comments>0)
4. cancelled 
5. waitlist
6. rejected
7. selected

**Comment by vnbang2003** [comment]
@ChillarAnand  Am not able to understand the metrics from point of view of organizing team.

**Comment by ChillarAnand** [comment]
if a proposal section looks like this
```
Core Python - reviewed(0), unreviewed(10), total(10)
```
organizing team don't know whether the assigned reviewers has checked the proposals and provided feedback or not.

On the other hand if we have something like this
```
Core Python - public(10), reviewing(0), reviewed(0), total(10)
```
organizing team can ping reviewers to review the proposals and
if reviewers has checked proposals and gave  some feedback it will look like this
```
Core Python - public(5), reviewing(5), reviewed(0), total(10)
```

**Comment by vnbang2003** [comment]
@kracekumar @ChillarAnand Let sync up tomorrow to discuss further as it think it meet the purpose already it just doesn't count public comments

**Comment by vnbang2003** [comment]
@ChillarAnand   Presently proposal dashboard page show status based on reviewers comment not public comments hence i think this bug can be closed.
Which reviewers is commented and all is shown in reviewers dashboard.

Let me know if we can close it.
