### ISSUE TITLE
add coveralls to junction

### ISSUE THREAD

**Issue by ChillarAnand** [pythonindia/junction#237]
coverage report will be a reminder for contributors/reviewers about unittests

**Comment by theskumar** [comment]
@kracekumar ping. Can we enable the integration at https://coveralls.io/ please. We can then add the required things to README.md and .travis.yml

**Comment by kracekumar** [comment]
@theskumar Please go ahead!

**Comment by kracekumar** [comment]
@theskumar Do you want someone to work on it dev sprint here ?

**Comment by theskumar** [comment]
@kracekumar sure anyone can take it up. :)

**Comment by anistark** [comment]
Cumulated in PR #246

**Comment by theskumar** [comment]
@anistark please open a new issue for coverall integration.

**Comment by theskumar** [comment]
Sorry, typo - s/new issue/new pull request/, specifically for coverall integration.

**Comment by theskumar** [comment]
Ideally, when we say coveralls.io integration we mean that the coverage report generated at Travis CI will be reported to coveralls.io, that happens automatically, if you run the proper command for it inside Travsi CI and then we also show a badge in the README.md which indicates the % coverage.

You can checkout the coverall setup here:
1. https://github.com/fossevents/fossevents.in/ (see: coverage status in REAMDE.md)
2. https://github.com/fossevents/fossevents.in/commit/505de89dfd8aefe3c9dacd15935ca53f97fda7af
3. https://github.com/fossevents/fossevents.in/blob/master/.travis.yml#L6

**Comment by anistark** [comment]
Yes @theskumar On it.

**Comment by ankeshanand** [comment]
I've set travis.yml acc. to https://github.com/coagulant/coveralls-python.
PR #248
