### ISSUE TITLE
Add reviewed and unreviewed filter along with section for proposal page

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/junction#239]
In dashboard page we display section with reviewed and unreviewed number . We can't add hyperlink to pass filter or flag to filter reviewed and unreviewed proposal in url like proposal_type=2 or proposal_section=5.
Proposal is to add allow add filter like proposal_section=5&reviewed=1 and proposal_section=5&reviewed=0.

**Comment by anistark** [comment]
@ChillarAnand Working on this now..

**Comment by vnbang2003** [comment]
I see there is duplicate bug opened #246 and there is pull request also.
hence closing it to avoid confusion.
@anistark Any particular reason to open bug #246  ?
