### ISSUE TITLE
add content upload status to proposals list page 

### ISSUE THREAD

**Issue by ChillarAnand** [pythonindia/junction#242]
![jj](https://cloud.githubusercontent.com/assets/4463796/7664950/876dc01c-fbbf-11e4-9ca8-153613990953.png)

we can remove username from the page and can add content upload status, so it will be easy for reviewers

**Comment by vnbang2003** [comment]
@ChillarAnand  we had discuss about this more in details in ticket #145 . Can we close this as duplicate ?

**Comment by ChillarAnand** [comment]
yep. tracking here https://github.com/pythonindia/junction/issues/145
