### ISSUE TITLE
No option to remove upvote/downvote given on a proposal

### ISSUE THREAD

**Issue by animenon** [pythonindia/junction#252]
Supoose I give an up-vote to a proposal, then I am not able to remove my up-vote.
![image](https://cloud.githubusercontent.com/assets/6907950/7665738/2db43870-fbe3-11e4-8dd0-404083c0c10e.png) 
Upvote added.
![image](https://cloud.githubusercontent.com/assets/6907950/7665741/444634a8-fbe3-11e4-9435-4e14c9552e54.png)
down-voted and it automatically did totalvotes-2 whereas I wanted to just remove my upvote.

**Comment by kracekumar** [comment]
Once you enter the game, you can come out ;-) This is by design and we won't fix!
