### ISSUE TITLE
Filter proposals assigned to a reviewer

### ISSUE THREAD

**Issue by vanishan** [pythonindia/junction#256]
We list all the proposals with the filter criteria yet to be reviewed and review in progress. For a reviewer, its difficult to find out which proposal he/she is allocated as a reviewer as he has to open each proposal to see the existence of Reviewer tab.
We need to list all the proposals assigned to a reviewer. It would be good if the filter criteria is added under the filters yet to be reviewed and review in progress with title your proposals.

**Comment by pythonhacker** [comment]
Also add a view where I can quickly filter out proposals I have already reviewed (entered some comments) and proposals yet to review. Right now I see just one blanket view of __Proposals to Review_ _which contains stuff that I have already wrote comment on.

Maybe this is another bug, but I felt it was in same scope here.

**Comment by vanishan** [comment]
@kracekumar @vnbang2003,
This feature should be implemented at the earliest. With the existing proposals page its difficult for reviewer to find the talks assigned to him regardless of review status. This is a blocker for reviewers as they have to go through a number of proposals to find the one assigned to them once they add a comment, we cannot expect them to rely only on mail notification.

**Comment by kracekumar** [comment]
I have attached rough sketch.

![img_20150630_000113](https://cloud.githubusercontent.com/assets/311929/8415547/196d02d2-1ebd-11e5-821b-d44f46b0cc42.jpg)
![img_20150630_000134](https://cloud.githubusercontent.com/assets/311929/8415548/197c91ca-1ebd-11e5-95cd-4addd8fd7bbc.jpg)

@vanishan @pythonhacker @vnbang2003 @ChillarAnand Have a look.

We can move `Proposals for review` to new page. Link to the `Proposals for review` can be promptly displayed in home page for reviewers alone.

The page will display all the proposals assigned for reviews under separate section.

- Proposals will be displayed like home page but will have extra `comment` icon next to `type`, `section` label. `Comment` icon will be displayed if reviewer has left any comment in `Reviewer` section. Display icon next to label isn't good, but we will live with it. Hovering on icon should says `Left a review comment`.

#### Filters

As of now we don't have any filters. We should allow reviewers to filter by `sections`, `type`, `comments`.

- `sections` filter will have all sections like `infra, web`.
- `type` filter will have `workshop, talks`.
- `comments` filter will have `commented, yet to comment`. Later we will have option filter by `voting` option too.

All the filters should be implemented in JS, should be easy with `jquery`. Reviewer should be able to choose one or more filter. There should be an option to remove the filter. 

If any other filter makes sense, leave a comment.

**Comment by vnbang2003** [comment]
I personally feel we need to sit and redesign UI and give good thought.
We will surely have multiple thing coming into picture as i explained in #293 .
Once voting come in to picture few more thing will be added for reviewers.
With Organizer login we will end up showing more links. 
We even need to add schedule page also soon and if possible come with generic algorithm to automatically create schedule based on mark given by reviewers.

**Comment by kracekumar** [comment]
We will continue discussion in separate thread. We will have proper mockups
to discuss those. Let's discuss what can be improved in the mockup.

**Comment by ChillarAnand** [comment]
Closing as this is done. A bug is yet to fix https://github.com/pythonindia/junction/issues/299
