### ISSUE TITLE
empty space at the bottom 

### ISSUE THREAD

**Issue by ChillarAnand** [pythonindia/junction#257]
in all pages, there is lot of empty space between end of content and the footer. this should be removed.
here is a screenshot
![jj](https://cloud.githubusercontent.com/assets/4463796/7798666/45419a4e-031a-11e5-8f71-9df75ad67e14.png)

**Comment by kracekumar** [comment]
Yes please :-)

**Comment by mudassir0909** [comment]
@ChillarAnand Can you please point out to any specific URL ? it'll be easier that way

**Comment by ChillarAnand** [comment]
@mudassir0909 sorry for delay. looks like issue is fixed :+1:

**Comment by ChillarAnand** [comment]
this is not yet fixed. 

here is the screenshot
![spa](https://cloud.githubusercontent.com/assets/4463796/8438755/7f0bb660-1f85-11e5-8a1c-3d6e914e1a08.png)

url: http://127.0.0.1:8000/a-porro-conference/proposals/ or any list proposals view
