### ISSUE TITLE
link to dashboard

### ISSUE THREAD

**Issue by ChillarAnand** [pythonindia/junction#258]
for conferences we have dashboard, but there is not link to it to navigate there. 
may be add button in home page, next to conference name?

**Comment by vnbang2003** [comment]
I had added it . I think @kracekumar  had disabled it .

**Comment by vnbang2003** [comment]
@kracekumar @ChillarAnand  Lets make button visible only to admin. We even added Reviewers Dashboard. Should we make it tab view for dashboard ? I am not great with UI if someone can help it will be awesome.

**Comment by vnbang2003** [comment]
@kracekumar I think we can add new block which will be visible only to admin and add link to both the dashboard page. which will be displayed as in screenshot.

{% block dashboard_link %}
 {% endblock %}

![258](https://cloud.githubusercontent.com/assets/316253/8390950/202543e4-1ccb-11e5-9c8f-461332c1aafd.png)

**Comment by vnbang2003** [comment]
Do provide update and let me know if we can close ticket as we wont fix.

**Comment by kracekumar** [comment]
Can you point me to the url which will rendered on clicking `Proposal Dashboard, Reviewers Dashboard` ?

**Comment by vnbang2003** [comment]
it will point to Dashboard pages
 (1) Proposal Dashboard : cfp/pycon-india-2015/dashboard/
 (2) Reviewers Dashboard  cfp/pycon-india-2015/dashboard/reviewers/

**Comment by kracekumar** [comment]
We can refrain doing it now. We are adding Dashboard feature, we will
completely design it.

On Mon, Jun 29, 2015 at 9:39 PM, Vijay <notifications@github.com> wrote:

> it will point to Dashboard pages
> (1) Proposal Dashboard : cfp/pycon-india-2015/dashboard/
> (2) Reviewers Dashboard cfp/pycon-india-2015/dashboard/reviewers/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pythonindia/junction/issues/258#issuecomment-116745088>
> .
>



-- 
Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521

**Comment by vnbang2003** [comment]
As i have open new bug for NewTab/Page  which is basically redesign on page flow #293 .
I will add this point in that bug hence closing it for now.
