### ISSUE TITLE
Improving logging and event action history

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/junction#261]
We need to log all the action of each reviewers or any action button to help us analysis.
I would recommend doing two ways
1) Standard log file entry
2) use django-simple-hsitory(https://github.com/treyhunner/django-simple-history) to capture each action in DB.

**Comment by kracekumar** [comment]
- https://github.com/pythonindia/junction/blob/master/junction/proposals/models.py#L200
- https://github.com/pythonindia/junction/blob/master/junction/proposals/models.py#L66

Logging these two models should be good @hTrap.

**Comment by kracekumar** [comment]
We should able to filter on these logging by any one of the field. Say show me all `proposals modified based on review_status`.

**Comment by ananyo2012** [comment]
#330 fixed this
