### ISSUE TITLE
update login url in email messages

### ISSUE THREAD

**Issue by ChillarAnand** [pythonindia/junction#276]
when some one leaves comments on proposal, email sent to receipents has login url which redirects to home page.  this  should redirect to corresponding proposal instead of home page.

**Comment by kracekumar** [comment]
This is bad user experience. We should fix it.

On Sun, Jun 7, 2015 at 10:42 PM, Anand Reddy Pandikunta <
notifications@github.com> wrote:

> when some one leaves comments on proposal, email sent to receipents has
> login url which redirects to home page. this should redirect to
> corresponding proposal instead of home page.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pythonindia/junction/issues/276>.
>



-- 
Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521
