### ISSUE TITLE
Reviewer Coherence - Which reviewer am I talking to ?

### ISSUE THREAD

**Issue by pythonhacker** [pythonindia/junction#279]
Right now every comment by a __reviewer__ is shown as __reviewer__ only. This impedes coherent conversations cuz the proposer has no idea which reviewer he is talking to.

When I say __Which reviewer__ I dont mean the _actual identity_ of the reviewer. It is more like, __Am I talking to the same reviewer who had given me that interesting comment and which I followed up with changes, or is this someone else ?__

To help proposers in the discussion, suggest to change plain __reviewer__ to,
__reviewer[id]__ where id is a number assigned on a first cum first serve basis in the system. Think of them as tokens representing the reviewer in the system.

So __reviewer__ would become __reviewer1__, __reviewer2__ etc. Hence if a reviewer follows up with a comment, the proposer knows - __OK, this is the same dude who gave the comment #1__ .

If you really want to go esoteric, you could also use reviewer&lt;uuid&gt; as well. 

I am marking this as nice-to-have .

**Comment by kracekumar** [comment]
This is a good suggestion.

On Tue, Jun 9, 2015 at 6:16 PM, Anand B Pillai <notifications@github.com>
wrote:

> Right now every comment by a *reviewer* is shown as *reviwer* only. This
> impedes coherent conversations cuz the proposer has no idea which reviewer
> he is talking to.
>
> When I say *Which reviewer* I dont mean the *actual identity* of the
> reviewer. It is more like, *Am I talking to the same reviwer who had
> given me that interesting comment and which I followed up with changes, or
> is this someone else ?*
>
> To help proposers in the discussion, suggest to change plain *reviewer*
> to,
> *reviwer[id]* where id is a number assigned on a first cum first serve
> basis in the system. Think of them as tokens representing the reviewer in
> the system.
>
> So *reviewer* would become *reviewer1*, *reviewer2* etc. Hence if a
> reviewer follows up with a comment, the proposer knows - *OK, this is the
> same dude who gave the comment #1
> <https://github.com/pythonindia/junction/issues/1>* .
>
> If you really want to go esoteric, you could also use reviewer<uuid> as
> well.
>
> I am marking this as nice-to-have .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pythonindia/junction/issues/279>.
>



-- 
Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521

**Comment by theSage21** [comment]
Is this an acceptable fix? #281 
I personally find the usage of PK to be ugly but cannot think of anything simple at the moment.

**Comment by pythonhacker** [comment]
PK ? Can you clarify

**Comment by kracekumar** [comment]
PK, primary key

On Fri, Jun 19, 2015 at 10:51 PM, Anand B Pillai <notifications@github.com>
wrote:

> PK ? Can you clarify
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pythonindia/junction/issues/279#issuecomment-113536585>
> .
>



-- 
Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521

**Comment by dhilipsiva** [comment]
I think this can be closed now.

**Comment by kracekumar** [comment]
Yes, Just being cautious, if something comes up after deployment, we can
fix it and close it.

On Tue, Jun 23, 2015 at 12:04 PM, dhilipsiva <notifications@github.com>
wrote:

> I think this can be closed now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pythonindia/junction/issues/279#issuecomment-114347815>
> .
>



-- 
Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521

**Comment by dhilipsiva** [comment]
:+1:

**Comment by kracekumar** [comment]
Screen shot from local system 
![screen shot 2015-06-23 at 9 49 27 am](https://cloud.githubusercontent.com/assets/311929/8298890/4077f11e-198d-11e5-86d7-c708980bf7d4.png)

**Comment by dhilipsiva** [comment]
A bit confused. Is there a bug?

**Comment by kracekumar** [comment]
Nope :-)

On Tue, Jun 23, 2015 at 12:23 PM, dhilipsiva <notifications@github.com>
wrote:

> A bit confused. Is there a bug?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pythonindia/junction/issues/279#issuecomment-114350612>
> .
>



-- 
Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521

**Comment by kracekumar** [comment]
It is a general practice to upload screenshot if there is a change in UI or
new feature is added. I realised this after merging. From next time you can
add screenshot in description.

On Tue, Jun 23, 2015 at 12:26 PM, Kracekumar Ramaraju <me@kracekumar.com>
wrote:

> Nope :-)
>
> On Tue, Jun 23, 2015 at 12:23 PM, dhilipsiva <notifications@github.com>
> wrote:
>
>> A bit confused. Is there a bug?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/pythonindia/junction/issues/279#issuecomment-114350612>
>> .
>>
>
>
>
> --
> Regards
> Kracekumar Ramaraju
> http://kracekumar.com
> +91 85530 29521
>



-- 
Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521

**Comment by dhilipsiva** [comment]
Oh, okies. Did not know that. Will do that from this point forward. :stuck_out_tongue:

**Comment by kracekumar** [comment]
Code is live in server and everything looks good.

**Comment by pythonhacker** [comment]
Thanks for doing this @kracekumar .
