### ISSUE TITLE
sign in with google is not working

### ISSUE THREAD

**Issue by ChillarAnand** [pythonindia/junction#283]
when signin in with google, it is redirecting to signup page

**Comment by kracekumar** [comment]
It redirect to https://in.pycon.org/cfp/pycon-india-2015/proposals/#

**Comment by ChillarAnand** [comment]
@kracekumar  not sure what is causing this. i am still getting the error. but with github everything is working fine.

**Comment by ChillarAnand** [comment]
may be this https://github.com/pennersr/django-allauth/issues/215 ?

**Comment by theskumar** [comment]
This is working fine for me. 

Although, it created me a new account, I had signed up via github earlier.. not sure how you resolve this issue given the context.

**Comment by ChillarAnand** [comment]
my bad. google wasn't in social accounts

**Comment by kracekumar** [comment]
@theskumar If you use `allauth's ` default connection option `https://in.pycon.org/cfp/accounts/social/connections/#`, it will link multiple emails under same account.

@ChillarAnand I am able to login with Google and Github for same email id. Can you try incognito or different browser ?

**Comment by ChillarAnand** [comment]
@kracekumar  i have added google to social accounts. it is working fine for both google & github. no issues.
