### ISSUE TITLE
Change Reviewers heading to Reviews in comments section.

### ISSUE THREAD

**Issue by kracekumar** [pythonindia/junction#288]

**Comment by vnbang2003** [comment]
![288_junction](https://cloud.githubusercontent.com/assets/316253/8390877/76daf7b4-1cc7-11e5-8277-9a2240dd4acc.png)

**Comment by vnbang2003** [comment]
@kracekumar  ?

**Comment by kracekumar** [comment]
Yes. I meant "Reviews"

**Comment by ChillarAnand** [comment]
Also change glyphicons for `Reviews`  & `Reviewers Talk`
