### ISSUE TITLE
Section based closure date for CFP

### ISSUE THREAD

**Issue by kracekumar** [pythonindia/junction#291]
Conference consist of different types of sessions like `Talks, Workshops`. So far the all the past conferences had single closure date for both. Going forward junction should be flexible to collect projects/topics for `Dev Sprint, Flash Talks`.

Every session type can have start date and end date. If the session/proposal type has start date that should be counted or date given during conference creation should be counted.
### Proposal Submission

When a user visits the url to submit a new proposal, if CFP date is elapsed, custom message `CFP submission is closed` is displayed. If one of the section has custom date which is in present/future, user should be allowed to submit the talk. The proposal type user can choose should be accepting proposals. 

Say `talks, tutorials` last date for submission is `May, 30` and for `Dev Sprint` is `August 1`. Visiting the url (`/<conf-slug>/proposals/create/`) on July 30th should allow user to submit proposal under the type `Dev Sprint` only. Other two types shouldn't be displayed in the drop down and hackish work to malform the input data and submit should be caught at backend..
### Proposal Edit

After few days say on August 2, user shouldn't be allowed to change the session type. In general once closure date is elapsed user shouldn't be allowed to modify the type but can update details like `desc`, `links`. 

Though we're not displaying elapsed type in the drop down of the edit url, it is possible for user to change the html data via inspect element and with guess work. Backend should prevent it.

@dhilipsiva Can you pick up this task ?

**Comment by dhilipsiva** [comment]
Sure. I will take this up.

-- 
Cheers,

dhilipsiva

Full Stack & DevOps Engineer

http://dhilipsiva.com

+91 81 97 98 53 97

    


On 25 June 2015 at 00:22:41, Kracekumar Ramaraju (notifications@github.com) wrote:

Conference consist of different types of sessions like Talks, Workshops. So far the all the past conferences had single closure date for both. Going forward junction should be flexible to collect projects/topics for Dev Sprint, Flash Talks.

Every session type can have start date and end date. If the session/proposal type has start date that should be counted or date given during conference creation should be counted.

Proposal Submission

When a user visits the url to submit a new proposal, if CFP date is elapsed, custom message CFP submission is closed is displayed. If one of the section has custom date which is in present/future, user should be allowed to submit the talk. The proposal type user can choose should be accepting proposals.

Say talks, tutorials last date for submission is May, 30 and for Dev Sprint is August 1. Visiting the url (/<conf-slug>/proposals/create/) on July 30th should allow user to submit proposal under the type Dev Sprint only. Other two types shouldn't be displayed in the drop down and hackish work to malform the input data and submit should be caught at backend..

Proposal Edit

After few days say on August 2, user shouldn't be allowed to change the session type. In general once closure date is elapsed user shouldn't be allowed to modify the type but can update details like desc, links.

Though we're not displaying elapsed type in the drop down of the edit url, it is possible for user to change the html data via inspect element and with guess work. Backend should prevent it.

@dhilipsiva Can you pick up this task ?

**Comment by kracekumar** [comment]
@dhilipsiva Any updates on this ?

**Comment by dhilipsiva** [comment]
Not yet. I have been travelling since last week. Was this on a High-Priority? In any case, I will be working this on this Sunday.

-- 
Cheers,

dhilipsiva

Full Stack & DevOps Engineer

http://dhilipsiva.com

+91 819 77 93582

    


On 3 July 2015 at 11:25:40, Kracekumar Ramaraju (notifications@github.com) wrote:

@dhilipsiva Any updates on this ?

**Comment by kracekumar** [comment]
Weekend should be fine :-) Following up to confirm you're on track.

On Fri, Jul 3, 2015 at 11:54 AM, dhilipsiva <notifications@github.com>
wrote:

> Not yet. I have been travelling since last week. Was this on a
> High-Priority? In any case, I will be working this on this Sunday.
>
> --
> Cheers,
>
> dhilipsiva
>
> Full Stack & DevOps Engineer
>
> http://dhilipsiva.com
>
> +91 819 77 93582
>
>
>
>
> On 3 July 2015 at 11:25:40, Kracekumar Ramaraju (notifications@github.com)
> wrote:
>
> @dhilipsiva Any updates on this ?
>
>
> —
> Reply to this email directly or view it on GitHub.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pythonindia/junction/issues/291#issuecomment-118249432>
> .
>



-- 
Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521

**Comment by dhilipsiva** [comment]
I am not familiar with entire codebase. But is the following line correct? `proposal_sections` and `proposal_type` is swapped.
<img width="454" alt="screen shot 2015-07-08 at 23 43 29" src="https://cloud.githubusercontent.com/assets/502170/8578356/f3a720c6-25cb-11e5-9756-e82136029f5c.png">

**Comment by kracekumar** [comment]
AFAIK, it is swapped. Looks like @ChillarAnand wrote it.

**Comment by dhilipsiva** [comment]
@kracekumar `..if CFP date is elapsed, custom message CFP submission is closed...` The `submission is closed` message is not shown depending on date but on status. Just clarifying it so that there is no confusion.
<img width="436" alt="screen shot 2015-07-10 at 08 39 10" src="https://cloud.githubusercontent.com/assets/502170/8611473/2ca28078-26df-11e5-848f-d3bb4c972e74.png">

**Comment by dhilipsiva** [comment]
Apologies for taing so long on completing such simple task. Been caught up with both Full Timae and Part Time works lately. :P Does #307 Look good?

**Comment by kracekumar** [comment]
Yes that was previous assumption. Now we need to check for date.
