### ISSUE TITLE
Comments Preview

### ISSUE THREAD

**Issue by pythonhacker** [pythonindia/junction#292]
It would be nice to have a Preview of the comments before posting them so you can correct errors in the markdown.

Best template is right here - when I am writing these comments I can see a __Preview__ tab on the right of the __Write__ tab. 

![screenshot-new issue pythonindia-junction - mozilla firefox-1](https://cloud.githubusercontent.com/assets/316177/8346792/723d3a0e-1b1f-11e5-8781-2bb552aa1bf8.png)

**Comment by pythonhacker** [comment]
That makes for a nice recursive bug definition.

**Comment by kracekumar** [comment]
We have this for proposal submission, we should have this for comments too.

+1.

On Thu, Jun 25, 2015 at 9:50 AM, Anand B Pillai <notifications@github.com>
wrote:

> That makes for a nice recursive bug definition.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pythonindia/junction/issues/292#issuecomment-115098706>
> .
>



-- 
Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521

**Comment by kracekumar** [comment]
This is fixed in production. Preview is right below the comment text area.
