### ISSUE TITLE
new pages for multiple views

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/junction#293]
I think it time for Junction to have multiple page
1) Dashboard (To view his proposals, previous submit like mentioned  in #287  along with that we can add stats which display his reviews stats)
2) Reviewing (Page which display proposal list assigned to me for selected proposals).
3) Proposals (page which display all proposals including mine for that conference)

We even need to link two other dashboard used by organizer
(1) Proposal Dashboard : cfp/pycon-india-2015/dashboard/
(2) Reviewers Dashboard cfp/pycon-india-2015/dashboard/reviewers/

This will help first time user of junction to all features.

**Comment by theskumar** [comment]
@vnbang2003 it seems most of the functionality mentioned have been implemented. 

Can you verify that the desired functionality existing and list down any missing pieces. Thanks.

**Comment by vnbang2003** [comment]
Yep done. closing it
