### ISSUE TITLE
in list proposals page filtering should be done on frontend

### ISSUE THREAD

**Issue by ChillarAnand** [pythonindia/junction#296]
right now we are sending requests to server for every filtering. this should be avoided as we can filter in frontend itself.

**Comment by kracekumar** [comment]
@mudassir0909 Is there good way to implement this in client side ? Our recent experience with DOM manipulation is bad, tending to stay in server side, https://github.com/pythonindia/junction/blob/master/junction/templates/proposals/to_review.html#L78.

**Comment by mudassir0909** [comment]
yes there is but then if we go with jquery-only solution it'll be messy & harder to maintain. So, the solution is to use Backbone in the places where we wish to make parts of application ajax based.

**Comment by ChillarAnand** [comment]
As [discussed](https://github.com/pythonindia/junction/pull/297#issuecomment-118139744), we are sticking with server side filtering for now.
