### ISSUE TITLE
Registering mobile devices

### ISSUE THREAD

**Issue by kracekumar** [pythonindia/junction#298]
We're working on having mobile application for PyCon India. The app shouldn't ask username and password or have account creation steps. We need to have alternate way to identify each device uniquely.

This is similar to web application where a user registers and verify the details. Taking this to mobile, as soon as user installs the app client will generate `UUID1` and send to the server (user account is created). Now we need to confirm this is from client, now server will generate the random number and  send push notification to device using `GCM or APN`. Client will repost the number to server and now the device is successfully verified.

We don't want to send sms for verification, since it will be costly.

If the device is unverified all the write actions to server will throw `UnAuthorized`. 

Thoughts @pythonindia/ios @pythonindia/androidteam ?

**Comment by rishimukherjee** [comment]
I like the idea. +1

**Comment by kracekumar** [comment]
@dhilipsiva Can you take up this task ? We're using Django REST Framework for serving API.

**Comment by dhilipsiva** [comment]
Sure. But I cant work on this until Sunday. Running on a tight schedule. Please assign this to me if its not urgent.

**Comment by kracekumar** [comment]
No worries. You can start working next week :-)

**Comment by dhilipsiva** [comment]
Oh, great. In that case, I will take this up.

**Comment by kracekumar** [comment]
@dhilipsiva Let me know if you need any help from my side.

**Comment by dhilipsiva** [comment]
Oh shoot! I forgot about this. Will send a PR today.

**Comment by dhilipsiva** [comment]
@kracekumar Apologies on the delay. My wife and I had a baby boy last week. I am afraid I cannot take this up at the moment. I can surely work on this when I come back to Bangalore (Next week). But I am afraid I cant work on this until then. If this is not on priority, I can work on this next week.

**Comment by kracekumar** [comment]
No worries :-)

**Comment by kracekumar** [comment]
Fixed in https://github.com/pythonindia/junction/pull/355. We won't implement verification of device.

**Comment by dhilipsiva** [comment]
Oh, nice. Thanks. Sorry I could not fix this.

**Comment by kracekumar** [comment]
Never mind :-)

On Sun, Sep 6, 2015 at 6:32 PM, dhilipsiva <notifications@github.com> wrote:

> Oh, nice. Thanks. Sorry I could not fix this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pythonindia/junction/issues/298#issuecomment-138083553>
> .
>



-- 
Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521
