### ISSUE TITLE
Fix filters in `/to_review`

### ISSUE THREAD

**Issue by theskumar** [pythonindia/junction#299]
![a](https://www.dropbox.com/s/49brere0ko3jsq5/Screenshot_2015-07-06_07_12_19.jpg?dl=1)

The filter doesn't seem to work, verify and fix.

**Comment by kracekumar** [comment]
If only one filter is chosen the results works fine.

**Comment by kracekumar** [comment]
We're reimplementing this in backend. We will be able to get in two or three days.

**Comment by theskumar** [comment]
It's seems to be happening because of spaces in the attributes `id` and `data-type`.

Noticed the use of:

```
<div id="{{title}}">
```
where `id="Web Development"`, where instead a number id or slug should be used.

**Comment by theskumar** [comment]
It works fine if you don't have spaces in the filter select item. e.g. `yes/no` in reviewers comment.

**Comment by kracekumar** [comment]
@theskumar If I am right this commit https://github.com/pythonindia/junction/commit/16009a53462f58e3a287951e60b7fd25ea036d36 fixed right ?

**Comment by theskumar** [comment]
No it doesn't, i just improved some UI around it that's it. It requires a bit more of work to remove spaces in `id`.

**Comment by kracekumar** [comment]
@ChillarAnand Can you take this up ? One of your pull request you gave recently had similar code. You can abstract it out.
