### ISSUE TITLE
fix names of pre-registered reviewers names (before it's was implemented)

### ISSUE THREAD

**Issue by theskumar** [pythonindia/junction#300]
it seems the reviewers who had signed up before the number based reviewer name is implement for the same name `Reviewer`, it will be worth-while to either update their names or implement a rule to generate a name at realtime based of reviewer existing signature like database id or irreversible hash of his/her email/id.

**Comment by theskumar** [comment]
Some more context.
![a](https://www.dropbox.com/s/jaekh5jqnvyytcs/Screenshot%202015-07-06%2007.38.26.jpg?dl=1)

**Comment by kracekumar** [comment]
As of now, we added numbers for all. Can you confirm ?

**Comment by kracekumar** [comment]
Hope this isn't issue any more.

**Comment by kracekumar** [comment]
Please feel to reopen if things aren't working as expected.
