### ISSUE TITLE
Choice Fields (Or Enum equivalent) refactors

### ISSUE THREAD

**Issue by dhilipsiva** [pythonindia/junction#302]
I am working on Issue #291 . I cant help but notice the code snippets like `if conference.status != 1:`
from [junction/proposals/views.py](https://github.com/pythonindia/junction/blob/bc2cbae1fa97ed4fdf225988a0f794c446a0bcae/junction/proposals/views.py#L126) (It might be in some other places too). It is not immediately apparent what `1` represents. I have to open [junction/base/constants.py](https://github.com/pythonindia/junction/blob/bc2cbae1fa97ed4fdf225988a0f794c446a0bcae/junction/base/constants.py#L4) to cross-reference with the file and understand what it is. 

So I am raising an Issue here to propose a refactor. To deal with `choices` field I wrote a handy decorator. It goes something like this:

```python
import inspect


def user_attributes(cls):
    defaults = dir(type('defaults', (object,), {}))  # gives all inbuilt attrs
    return [
        item[0] for item in inspect.getmembers(cls) if item[0] not in defaults]


def choices(cls):
    """
    Decorator to set `CHOICES` attribute
    """
    _choices = []
    for attr in user_attributes(cls):
        val = getattr(cls, attr)
        _choices.append((val, attr))
    setattr(cls, 'CHOICES', tuple(_choices))
    return cls


@choices
class FooEnum:
    FOO = 1
    BAR = 2

print FooEnum.CHOICES  # Will contain `((2, 'BAR'), (1, 'FOO'))`
```

I also understand we might need some custom `get_<choice_field>_display` messages. For that I think we can tweak the choices decorator to do the same. That will be something like this.

```python
import inspect


def user_attributes(cls):
    defaults = dir(type('defaults', (object,), {}))  # gives all inbuilt attrs
    return [
        item[0] for item in inspect.getmembers(cls) if item[0] not in defaults]


def choices(cls):
    """
    Decorator to set `CHOICES` and other attributes
    """
    _choices = []
    for attr in user_attributes(cls):
        val = getattr(cls, attr)
        setattr(cls, attr[1:], val[0])
        _choices.append((val[0], val[1]))
    setattr(cls, 'CHOICES', tuple(_choices))
    return cls


@choices
class FooEnum:
    _FOO = [1, "Some Foo String"]
    _BAR = [2, "Some Bar String"]

print FooEnum.CHOICES  # ((2, 'Some Bar String'), (1, 'Some Foo String'))
print FooEnum.FOO  # 1
```

So we could do something like `if conference.status != ConferenceStatus.ACCEPTING_CFP:` which makes code base A bit readable and pragmatic. 

Any thoughts @kracekumar ?

**Comment by rmad17** [comment]
:+1:  Support @dhilipsiva 's point.

**Comment by kracekumar** [comment]
+1 for enum. Please go ahead.

**Comment by dhilipsiva** [comment]
This Issue can be closed, if there are no related bugs.

**Comment by dhilipsiva** [comment]
@kracekumar I created a stand alone decorator for doing this [dhilipsiva/orm-choices](https://github.com/dhilipsiva/orm-choices). Would it be okay if I refactored this code to use the `orm-choices` library and send a PR?

**Comment by kracekumar** [comment]
@dhilipsiva Sure, but one feature which will be useful is reverse lookup. If choice `Public` is `1`, db contains `1`, while returning the data via api, field need to bare the value as `Public` not 1.
