### ISSUE TITLE
Sponsorship Page

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/junction#31]
add sponsorship page and section to display sponsor's.

The Tab on top of page should have sub tab as 
1) Sponsors
2) Sponsorship prospectus 
    a) Display prospectus details
    b) Downloadable pdf link 
    c) Contact us form for any queries
3) Why Sponsor PyCon India 
4) Sponsorship information page
      It should display details like stall size , banner and benefit in more details .
      It should display information what PyCon India team will provide and what they need to get.
      It should display information on guidelines of goodies distribution.

Each Sponsor's logo size differ on sponsorship slots.

**Comment by theskumar** [comment]
It seems these feature can't really be part of the junction, they are better suited to be included as part of main conference website or landing page. 

It would be little too much to maintain these features in a software meant to manage proposals. 

I'm closing this, but feel free to re-open if you think it make sense to have these feature even now.
