### ISSUE TITLE
Voting option in proposal page

### ISSUE THREAD

**Issue by kracekumar** [pythonindia/junction#312]
When a reviewer goes to proposal page for `section` which is assigned to him, show a button to cast the vote like 

![screen shot 2015-07-19 at 9 31 17 pm](https://cloud.githubusercontent.com/assets/311929/8766618/ad5598ba-2e5d-11e5-8836-196566b0c7f9.png)

Click on the button should go to voting page `http://localhost:8000/<conference>/proposals/<proposal>/vote/`.

Reviewer should be allowed to leave a comment.

If the reviewer has already casted the vote message should be displayed.

![screen shot 2015-07-19 at 9 48 05 pm](https://cloud.githubusercontent.com/assets/311929/8766692/e0e3a882-2e5f-11e5-8e04-451d104151cd.png)

The newly submitted vote should be updated in DB.

### Review list page

If the reviewer has casted the vote `fa-check` icon should displayed.

![screen shot 2015-07-19 at 9 56 34 pm](https://cloud.githubusercontent.com/assets/311929/8766733/2245eabe-2e61-11e5-90b8-3882fd660b6e.png)

Tooltip should say "You have casted the vote"

**Comment by ChillarAnand** [comment]
> Reviewer should be allowed to leave a comment.

Not sure about this. Reviewers can leave a comment in comment section?

**Comment by kracekumar** [comment]
No this comment to say why they are voting +1 or -1. Probably call it as justification ?

**Comment by ChillarAnand** [comment]
Still didn't understood :( 
Whether  they are voting +1  or -1, can be  known from  the  vote value itself?

**Comment by kracekumar** [comment]
If reviewer says -1. We want to know why it is -1 right ? It can be because
the content is not upto level or speaker didn't follow up. We need capture
the info. This info is viewable only by the reviewer and admin team. Other
reviewers/proposers aren't allowed to see this.

On Mon, Jul 20, 2015 at 10:21 PM, Anand Reddy Pandikunta <
notifications@github.com> wrote:

> Still didn't understood :(
> Whether they are voting +1 or -1, can be known from the vote value itself?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pythonindia/junction/issues/312#issuecomment-122947641>
> .
>



-- 
Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521

**Comment by ChillarAnand** [comment]
Ok. In voting view, we will  show  this comment to corresponding  reviewer only. 

For admin, we can have  a new view where  we will show (score of prop0sal)/(max score) and all vote comments by all reviewers?

**Comment by kracekumar** [comment]
Yes it will be shown as part of https://github.com/pythonindia/junction/issues/314.
