### ISSUE TITLE
Getting a blank page upon voting

### ISSUE THREAD

**Issue by pythonhacker** [pythonindia/junction#325]
Wondering if this is correct. I think it should return some feedback saying your vote is recorded or better give options for upvote/downvote etc.
![screenshot from 2015-07-30 12 00 17](https://cloud.githubusercontent.com/assets/316177/8977029/a48bcff8-36b2-11e5-9cc3-a5006a8ef252.png)

**Comment by kracekumar** [comment]
@ChillarAnand Can you have a look at this ?

**Comment by ChillarAnand** [comment]
@kracekumar Wifi not working. Will checkout tomorrow.

**Comment by kracekumar** [comment]
@pythonhacker Can you verify this is fixed ?

**Comment by pythonhacker** [comment]
Fixed
