### ISSUE TITLE
Comment voting should use ajax

### ISSUE THREAD

**Issue by ChillarAnand** [pythonindia/junction#327]
In proposal detail page, proposal up/down vote uses ajax. Same should be used for comment voting also. Right now it is reloading entire page.

**Comment by jibin-jacob-jose** [comment]
Working on this

**Comment by nava45** [comment]
I am looking into it

**Comment by jklmn13** [comment]
@nava45  Do you mind, if I work on it

**Comment by nava45** [comment]
Please go ahead.

On Fri, Mar 11, 2016 at 3:17 PM, jaocb <notifications@github.com> wrote:

> @nava45 <https://github.com/nava45> Do you mind, if I work on it
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pythonindia/junction/issues/327#issuecomment-195297977>
> .
>



-- 
Navaneethan R,
call me: +91 959 120 4532,
tech <http://navaspot.wordpress.com> | me
<http://navaneethanit.wordpress.com>

Thank you my friend for our beautiful conversation which
brings harmonious between us hopefully.
