### ISSUE TITLE
Add spreadsheet export for ReviewerVotes

### ISSUE THREAD

**Issue by kracekumar** [pythonindia/junction#333]

**Comment by ChillarAnand** [comment]
![img_0254](https://cloud.githubusercontent.com/assets/4463796/9338165/e0af59c0-4600-11e5-813c-961c24b3c4f8.JPG)

Color code:

```
One  or  more -1 vote -> Red
Atleast two +2  votes and  no -1 votes -> Green
No of reviewer votes < two ->  Orange
```

@kracekumar @vnbang2003  Can  you  verify color code?
