### ISSUE TITLE
No dropdown for proposal section

### ISSUE THREAD

**Issue by tapasweni-pathak** [pythonindia/junction#334]
In submit a proposal [here](https://in.pycon.org/cfp/pycon-india-dev-sprint-2015/proposals/create/),
there is no dropdown in [proposal section](https://gyazo.com/0458a807c15eaa55344dd41aa30ad86b) which is mandatory field. Without this, it is [not allowing](https://gyazo.com/fefd53ee9a71f26e9d6194cc9431f961) me to submit the proposal.

**Comment by vnbang2003** [comment]
@tapasweni-pathak Thanks for point it out. I have add 3 section 1)Python (2) Django (3) Others.
@sayanchowdhury Can you please list down section so we can add it.

**Comment by vnbang2003** [comment]
Closing it now. Please re-open if you face same issue.
