### ISSUE TITLE
Comment count in proposal list page should consider public comments not reviewers count

### ISSUE THREAD

**Issue by kracekumar** [pythonindia/junction#337]
https://in.pycon.org/cfp/pycon-india-2015/proposals/getting-started-with-ansible/ has not comments, but it shows 1.

**Comment by ChillarAnand** [comment]
This proposal has https://in.pycon.org/cfp/pycon-india-2015/proposals/python-traceback-for-humans/ only  1 comment but it is showing 2 in dashboard.

![t2](https://cloud.githubusercontent.com/assets/4463796/9568131/d182b57a-4f5e-11e5-876b-9a2a7d0f1ad1.png)
