### ISSUE TITLE
Unable to login with github

### ISSUE THREAD

**Issue by theSage21** [pythonindia/junction#345]
I have previously registered with github.

When I try to login with Github, it simply says Social Network Login Failure.

**edit**
![screenshot from 2015-08-22 12 39 54](https://cloud.githubusercontent.com/assets/7693265/9422959/f29f11ee-48ca-11e5-8195-41a9531ed544.png)

This is encountered only when I try to login from the link provided in the email for updating talk content.
<http://in.pycon.org/cfp/accounts/login/?next=/cfp/pycon-india-2015/proposals/offline-programming-judge-in-python/>

Login fails with this link.
I am able to login otherwise if I simply open the talk and login.

**Comment by kracekumar** [comment]
@vigneshsarma can you have a look ?

**Comment by theskumar** [comment]
@theSage21 thanks a lot for reporting but this is no longer valid it seems. Please reopen this ticket if you think the issue is still persisting on your end.
