### ISSUE TITLE
Show all proposal in list page

### ISSUE THREAD

**Issue by kracekumar** [pythonindia/junction#352]
Proposal list page should show all proposals, right now it is not showing logged in user's proposals.

**Comment by ChillarAnand** [comment]
Looks like it is resolved  on `master`?

**Comment by kracekumar** [comment]
Yes, I fixed yesterday.

On Sun, Sep 6, 2015 at 7:51 PM, Anand Reddy Pandikunta <
notifications@github.com> wrote:

> Looks like it is resolved on master?
>
> —
> Reply to this email directly or view it on GitHub.
>



-- 
Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521
