### ISSUE TITLE
Add user profile 

### ISSUE THREAD

**Issue by kracekumar** [pythonindia/junction#364]
When a user signup, we create Django User Object. We need to create a profile object (`OneToOne` relationship), but this should be optional.

`https://in.pycon.org/cfp/profiles/` currently displays all proposals by a user. We need to store `City`, `Phone`. This info is useful when talks get selected. 

User should be able to edit `City/Phone`. Phone number should be string field.

**Comment by sjose1x** [comment]
- Create a new model Profile with one to one relationship with user.
- Add City/Phone fields 
- Create/Edit form

**Comment by sjose1x** [comment]
I'm on it.. Thanks

**Comment by theskumar** [comment]
@sjose1x is it possible to test your implementation somewhere?

**Comment by RishabhJain2018** [comment]
@theskumar Can I work on this ?

**Comment by RishabhJain2018** [comment]
@kracekumar @theskumar  Please tell me where will you take the input of city, phone from user . Also brief me about the Create/Edit Form.

**Comment by theskumar** [comment]
It will happen just after registration and should be editable via user > edit profile menu item.

**Comment by theskumar** [comment]
@kracekumar @RishabhJain2018  what's the status of this issue?

**Comment by RishabhJain2018** [comment]
@kracekumar I will be fixing this.

**Comment by kracekumar** [comment]
@RishabhJain2018 Any update?

**Comment by RishabhJain2018** [comment]
@kracekumar I had fixed the issue. Please refer to the PR #469 .

**Comment by kracekumar** [comment]
My bad @RishabhJain2018.

**Comment by RishabhJain2018** [comment]
@kracekumar No problem.

**Comment by satyanash** [comment]
PR #469 merged. This issue can be closed.
