### ISSUE TITLE
Remove unnecessary  info from cfp page

### ISSUE THREAD

**Issue by ChillarAnand** [pythonindia/junction#365]
![jj](https://cloud.githubusercontent.com/assets/4463796/10119110/4c640180-64aa-11e5-954d-9a6c261f1055.png)

In cfp page, guidelines, faq are displayed for each event. We can just display name & description.Guide lines  & FAQ can be added in correspoding pages.

**Comment by theskumar** [comment]
Just for clarification, the FAQs and other sections are part of the description. I'm happy if we just keep the  title and meta info currently displayed. 

This is good candidate for new comers to it up.

**Comment by theskumar** [comment]
This is now in master and deployed.
