### ISSUE TITLE
User should be able to connect social accounts

### ISSUE THREAD

**Issue by kracekumar** [pythonindia/junction#366]
Proposer can login via `Github/Google`. We should allow proposers to connect their `Facebook/Twitter/Github/LinkedIn` page so it will give good view of proposer technical competency.

All social accounts should be displayed automatically in `Speaker Info` section.

**Comment by shashankaryan** [comment]
Hey, I am working on this issue.

**Comment by ananyo2012** [comment]
#513 seems to add support for LinkedIn, Twitter, Facebook but it was removed in #528 . @kracekumar Any reason for the change ?

**Comment by kracekumar** [comment]
I don't remember correctly now. Feel free to take the decision of your own now.

**Comment by kracekumar** [comment]
I think, we want to use only details, what they put in their bio.

**Comment by pradyunsg** [comment]
I'm included to say that it's perfectly fine to avoid adding in social logins. Definitely not Facebook, Twitter et al, whose revenue model relies on Advertising / data collection.

**Comment by palnabarun** [comment]
@pradyunsg I agree with you, but we do have OAuth login through Google at the moment.

I think the current options are adequate at the moment. IMHO, it is highly unlikely that someone won't have either Google or a GH account. Even in that case, we allow signups from the platform itself.

In short, I am in favor of closing this.
