### ISSUE TITLE
Changing the title does not update the url

### ISSUE THREAD

**Issue by indradhanush** [pythonindia/junction#370]
Here's a link to my proposal: 
https://in.pycon.org/cfp/pycon-india-2015/proposals/time-travel-with-python/

Initially the title was:
**Time travel with Python**

And I changed it to:
**Avoiding common pitfalls of datetime from a webapp's perpective**

The url remains the same. The url should be updated to reflect the new title, while also making sure that the url with the older title redirects to the new one.

**Comment by theskumar** [comment]
A valid point, and it does make sense to be able to update the url. @indradhanush thanks for reporting this.

@kracekumar @ChillarAnand I propose to use an alternate url scheme for proposals using a option unique id along with the slug, if the unique id is present use that to redirect to the correct sluggifed url. (slug being generated on-the-fly at the request time), thoughts?

The url scheme would be 
```
<conference-slug>/proposals/<proposal-slug>/<hashid>/
```
---

The following url `<conference-slug>/proposals/<old-proposal-slug>/` would redirect to `<conference-slug>/proposals/<proposal-slug>/<hashid>/`

**Comment by kracekumar** [comment]
@theskumar As long as existing urls work, I am ok for the change.
