### ISSUE TITLE
Voting shouldn't be allowed post conference

### ISSUE THREAD

**Issue by sivaa** [pythonindia/junction#372]
Voting on the proposals shouldn't be allowed after the talks/schedule is finalized.

**Comment by sjose1x** [comment]
How can I reproduce this issue..?

**Comment by sjose1x** [comment]
Hi, 
I'm working on this issue.

**Comment by theskumar** [comment]
@sjose1x Any updates on this?

**Comment by sjose1x** [comment]
@theskumar Please have a look..

**Comment by smtchahal** [comment]
I want to work on this issue, but just to be clear, does this refer to the reviewer votes (`ProposalSectionReviewerVote`) or users' up votes/down votes (`ProposalVote`)?

**Comment by theskumar** [comment]
@smtchahal i think this has already been taken care off. You may like to cross check. And yes this for both.

**Comment by smtchahal** [comment]
We should still probably add tests that check for this though, because I'm not yet sure what disallowing voting post-conference means. Does that mean voting on a conference's proposals isn't allowed if the conference starts in the future (tomorrow or later) or that the conference's status is accepting proposals  and/or accepting votes? Or both?

**Comment by kracekumar** [comment]
It is checked here https://github.com/pythonindia/junction/blob/fe98c691b299a66588af670c3b422cd5a3437ad9/junction/proposals/views.py#L190. You're right, we need to add test case. Can you add test case ?

**Comment by smtchahal** [comment]
That seems to prevent votes against conferences that start in the future, and it only seems to work for user votes (not reviewer votes). Is that intended? Also, someone can still vote on the proposals by sending a POST request to the appropriate URL with the appropriate headers &ndash; there's no protection in `vote_views.proposal_vote`.

I suggest adding a `allows_voting` method in `models.Proposal` that returns whether or not the proposal can be voted on. `can_vote` can then be removed from the context served in `detail_proposal` and we can call the method in the template as well as in `vote_views` to check for this.

**Comment by kracekumar** [comment]
> Also, someone can still vote on the proposals by sending a POST request to the appropriate URL with the appropriate headers – there's no protection in vote_views.proposal_vote.

Good catch. There should be a check.

> I suggest adding a allows_voting method in models.Proposal

No coupling logic to model.

> it only seems to work for user votes (not reviewer votes).

Can you point out the code snippet which allows this ?

**Comment by smtchahal** [comment]
> Can you point out the code snippet which allows this ?

Well there's nothing in the code that prevents this. You can confirm this by logging in as admin, creating a proposal in a conference with a past create date in a particular section, then making admin a conference reviewer and then a proposal section reviewer for that section. You can't up vote or down vote on the proposal, that works as expected, but you can still cast a reviewer's vote if you are an authorized reviewer.

> No coupling logic to model.

You could add it in `proposals.permissions`, then, all similar functions are defined there. My point was it should be defined as a function in one place so we can perform checks by calling this function wherever necessary.

Also, I'm still not sure what counts as post-conference: conferences that started before today or does it also include the conference status (accepting proposals and accepting votes vs closed and schedule published)? Currently only the create date is checked, as you pointed out.

**Comment by kracekumar** [comment]
> Also, I'm still not sure what counts as post-conference: conferences that started before today or does it also include the conference status (accepting proposals and accepting votes vs closed and schedule published)? Currently only the create date is checked, as you pointed out.

Rather than relying on the date, any conference which is not in `Schedule Published` status can accept voting.

I am ignoring the admin use case you pointed. Since that can be done by the superuser. 

Would you like to make the change ?
