### ISSUE TITLE
There is not any 'create proposal' options for conferences which are in the 'Accepting Proposal'  status

### ISSUE THREAD

**Issue by sjose1x** [pythonindia/junction#376]
There is not any 'create proposal' options for conferences which are in the 'Accepting Proposal'  status
![Uploading Screen Shot 2015-10-24 at 4.06.52 pm.png…]()

**Comment by kracekumar** [comment]
These are two disconnected things. Unfortunately it can't be automated and manually modified in admin page.

**Comment by ChillarAnand** [comment]
Hopefully that answers your question. Feel free to reopen if you have any other issues.
