### ISSUE TITLE
Not able to install uwsgi requirement on Windows

### ISSUE THREAD

**Issue by gangadharmgithub** [pythonindia/junction#378]
pip install -r requirements-dev.txt  fails with below error while installing uwsgi on Windows operating system.

------------------------------------
Traceback (most recent call last):
File "setup.py", line 3, in <module>
import uwsgiconfig as uc
File "c:\Users\Gangadhar\python-training\junction\uwsgi-2.0.11.2\uwsgiconfig.p
y", line 8, in <module>
uwsgi_os = os.uname()[0]
AttributeError: 'module' object has no attribute 'uname'
-----------------------------------------

**Comment by ChillarAnand** [comment]
uswgi is required only for production. You can open `requirements.txt` remove `uwsgi` and continue.

If you need to install it on windows you need cygwin. Check [out this](http://stackoverflow.com/a/32165052/2698552).
