### ISSUE TITLE
Remove/refactor repeated code and add test cases

### ISSUE THREAD

**Issue by kracekumar** [pythonindia/junction#388]
Lot of code is repeated across apps, club them and remove the repeated tests. Add relevant test cases.

**Comment by ChillarAnand** [comment]
@kracekumar  Completed?

**Comment by kracekumar** [comment]
@ChillarAnand Nope. I am on halfway, but will jolt down list of points to speed up the development.

**Comment by kracekumar** [comment]
#397 does repeated code refactor. Test Cases are pending.

**Comment by kracekumar** [comment]
## Test cases

### User creation
[ ] - Create a new user with user name and password
[ ] - Login
[ ] - Profile creation

### Proposal

[ ] - Create new proposal
[ ] - Edit proposal
[ ] - Delete proposal
[ ] - View proposal
[ ] - Filter proposals by type and section

### Reviewer

[ ] - Reviewer private comment
[ ] - Reviewer vote
[ ] - Reviewer Internal comment

### Proposal Comment

[ ] - Public comment

**Comment by kracekumar** [comment]
Closed via https://github.com/pythonindia/junction/pull/401
