### ISSUE TITLE
Reviewer Section

### ISSUE THREAD

**Issue by sivaa** [pythonindia/junction#39]
When a reviewer logged in, additional tab should be displayed with the review comments(Private comments).

**Comment by vigneshsarma** [comment]
## Reviewer Section Proposal.
- Conference has many reviewers to review proposals
- A reviewer is a normal user on the system.
- Reviewer section in each proposal.
  - should differentiate between reviewers comment and users comment.
- Private Comment
  - Visible to All reviewers on conference, the user who proposed.
- Make some one a reviewer
  - From admin page given Conference, reviewer.

## possible future enhancements
- A reviewer can be in charge of a subsection of proposals
- There should be stages through which each proposal goes through.

@sivaa @kracekumar  If this is ok I will start working on it. Do suggest anything I have missed out.

**Comment by sivaa** [comment]
@vigneshsarma It looks good.
