### ISSUE TITLE
Conference admin control

### ISSUE THREAD

**Issue by kracekumar** [pythonindia/junction#403]
Currently Django admin is used to control all `conference, reviewers, feedback questions, reviewer internal questions`. Site admin is allowed to manage all these features. Every year conference admins are different. Conference admin should be allowed to add new `reviewers`, configure `questions` rather than site admin. Site admin should be allowed to change details across conference.

Admin site requires ACL depending on conference. Django admin or custom UI can be used. Django admin UI is customisable and using existing UI will save lot of time.

@ChillarAnand can you work on it ?

**Comment by ChillarAnand** [comment]
We can create a group and then assign required permissions to moderator. Will that be sufficient? @kracekumar

**Comment by kracekumar** [comment]
Not sure this will work. Can you quickly prototype and push in some branch ?

**Comment by ChillarAnand** [comment]
Fixed in #414
