### ISSUE TITLE
Installing requirements wouldnt work

### ISSUE THREAD

**Issue by ramaseshan** [pythonindia/junction#404]
So I downloaded the code, and did a 

`pip install -r requirements-dev.txt`

and it wouldnt work.

following is the trace log : 

> Exception:
> Traceback (most recent call last):
>   File "/junction/lib/python2.7/site-packages/pip/basecommand.py", line 134, in main
>     status = self.run(options, args)
>   File "/junction/lib/python2.7/site-packages/pip/commands/install.py", line 220, in run
>     for req in parse_requirements(filename, finder=finder, options=options):
>   File "/junction/lib/python2.7/site-packages/pip/req.py", line 1477, in parse_requirements
>     req = InstallRequirement.from_line(line, comes_from, prereleases=getattr(options, "pre", None))
>   File "/junction/lib/python2.7/site-packages/pip/req.py", line 129, in from_line
>     return cls(req, comes_from, url=url, prereleases=prereleases)
>   File "/junction/lib/python2.7/site-packages/pip/req.py", line 44, in __init__
>     req = pkg_resources.Requirement.parse(req)
>   File "/junction/lib/python2.7/site-packages/pkg_resources.py", line 2914, in parse
>     reqs = list(parse_requirements(s))
>   File "/junction/lib/python2.7/site-packages/pkg_resources.py", line 2839, in parse_requirements
>     line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
>   File "/junction/lib/python2.7/site-packages/pkg_resources.py", line 2817, in scan_list
>     "Expected ',' or end-of-list in",line,"at",line[p:]
> ValueError: ("Expected ',' or end-of-list in", 'dj-database-url==0.3.*', 'at', '*')
>

**Comment by gprakhar** [comment]
Same issue.
I figured out what exactly the issue is.
The star for globing at end of the package name: 
`dj-database-url==0.3.*`
is causing the error.
If you comment this line and rerun the command, it again gives same error for different line:
` uwsgi==2.0.*`

What is the exact package version to be used here for dj-database-url & uwsgi ?

**Comment by kracekumar** [comment]
Can you do `pip install -U pip` and `pip install -r requirements-dev.txt` ?

**Comment by gprakhar** [comment]
Is the first command is to be executed inside the virtenv created for junction ?

**Comment by gprakhar** [comment]
First activate your virtual env.
Install 'pg_config' tool, which is in postgresql-devel package (libpq-dev in Debian/Ubuntu)
Execute the commands mentioned by Kracre above.
It works!! Please mark resolved.

**Comment by kracekumar** [comment]
Yep, both inside virtualenv.
