### ISSUE TITLE
Footer Correction

### ISSUE THREAD

**Issue by PeeyushAgg** [pythonindia/junction#420]
Someone in Mailing list pointed out the outdated copyright year.

Please update the copyright year in ```junction/mkdocs.yml``` from ```2015``` to ```2016```

**Comment by ChillarAnand** [comment]
Thanks for opening issue here.

It is already fixed in https://github.com/pythonindia/junction/pull/417

**Comment by theskumar** [comment]
As pointed out, this just requires a new deployment. Closing this now.
