### ISSUE TITLE
Documentation for junction

### ISSUE THREAD

**Issue by sivaa** [pythonindia/junction#43]
- Creating a Conference
- Creating Conference Moderators
- Creating Conference Proposal Reviewers
- Creating Conference Sections
- Creating Conference Types
- Adding allauth tokens

**Comment by theskumar** [comment]
@sivaa can we have a proper documentation using [mkddocs](http://www.mkdocs.org/) instead of having it all inside Readme.md to be sane and scaleable. Thoughts?

We can host the docs as proper readthedocs type website at http://pythonindia.github.io/junction if we want.

I can help setting up the initial pages.

**Comment by sivaa** [comment]
@theskumar Sure. Its a good idea.

**Comment by theskumar** [comment]
I've added the initial documentation setup here: https://github.com/pythonindia/junction/commit/6da6e9fd5c695eccb7c173fb0a6d049f6b4b772d

Available at https://pythonindia.github.io/junction/ . updated by running `mkdocs gh-deploy` command.

**Comment by kracekumar** [comment]
We have agreed to use mkdocs. Now we need to add documentation for setting up junction with screen shots.

**Comment by kracekumar** [comment]
We need to start writing documentation. Documentation should contain `setup instruction, how tos, features` etc for phase one.

### How tos

- Set up a conference
- Add reviewers for a conference
- Assign Section reviewers
- Private Comments
- Reviewers only collaboration

### Features

One liner/small writeup about existing features.

### Setup

- How to setup third party packages like django-allauth (links to existsing one is also fine)
- setting up special settings variables.

Thoughts ? @sivaa @theskumar @vanishan @vnbang2003 @ChillarAnand @vigneshsarma @pythonhacker and others.

**Comment by ananyo2012** [comment]
Moved to #627
