### ISSUE TITLE
Proposal voting does not return to 0 on +-1

### ISSUE THREAD

**Issue by theSage21** [pythonindia/junction#433]
To recreate  

- Create a proposal
- Upvote
- Downvote
- Watch bug in action

Proposal switches between -1 and +1.  
+1, -1 should return votes to zero right?

**Comment by theskumar** [comment]
No, either to upvote or downvote a proposal. To remove your vote, you would need to click on the `upvote` or `downvote` icon once again. Let me know if this clears up the confusion.

**Comment by theskumar** [comment]
I'm closing the ticket for now to keep things sane, reopen the ticket as necessary! Thanks for all the help @theSage21!

**Comment by theSage21** [comment]
Right, it does. I was just about to close it. :+1:
