### ISSUE TITLE
Make it easy to navigate though proposals in a section

### ISSUE THREAD

**Issue by anandology** [pythonindia/junction#439]
Right now Junction don't have a way to navigate through proposals of a section. For this we need to add next/prev links to a proposal page and also they should understand which section the user currently in.

Good example of this pattern is navigating though photos in a flickr set. 

https://www.flickr.com/photos/kushaldas/15243627367/in/album-72157648319479582/

It is showing photo 15243627367, in the context of album 72157648319479582. So the next/prev links works in the album.

You could either use nice URLs are reported in #437, or just use the section as a query string when displaying the talk.

Either 

https://in.pycon.org/cfp/2016/proposals/demystifying-the-django-rest-framework~dBNxd/in/section-web-development

or 

https://in.pycon.org/cfp/2016/proposals/demystifying-the-django-rest-framework~dBNxd/?section=web-development

**Comment by ananyo2012** [comment]
Seems like #437 will fix this issue. Hence closing.
