### ISSUE TITLE
Proposal undo upvote/downvote doesn't works

### ISSUE THREAD

**Issue by aktech** [pythonindia/junction#441]
To Recreate:

1. Go to any proposal
2. Either upvote or downvote
3. Now press on the same upvote or downvote button (exactly what you did in previous step) to undo your vote.
4. That doesn't works.

See the bug in action.

**Comment by smtchahal** [comment]
Just sent in a pull-request that fixes this. I would add tests, but I couldn't find a suitable test module. Let me know what you think.

**Comment by aktech** [comment]
ping @theskumar @kracekumar
