### ISSUE TITLE
Proposal comment count is off

### ISSUE THREAD

**Issue by theSage21** [pythonindia/junction#443]
I am unable to point out the source of this but the proposal comment count on the main page is wrong.  

There are two comments on my proposal and the main proposal list shows three.
![screenshot from 2016-06-23 09-51-05](https://cloud.githubusercontent.com/assets/7693265/16291816/a16a1a86-3928-11e6-8b14-cfc9c59b1e0d.png)
![screenshot from 2016-06-23 09-51-25](https://cloud.githubusercontent.com/assets/7693265/16291818/a171be30-3928-11e6-9651-c345b913dde2.png)
![screenshot from 2016-06-23 09-51-32](https://cloud.githubusercontent.com/assets/7693265/16291817/a17104f4-3928-11e6-8377-290ce2e7e6f8.png)

**Comment by kracekumar** [comment]
@theSage21 It's fixed now. Thanks for reporting.

![screen shot 2016-06-23 at 12 45 14 pm](https://cloud.githubusercontent.com/assets/311929/16294514/ba691c9c-393e-11e6-868d-249717d887ed.png)

**Comment by theSage21** [comment]
@kracekumar thank you :+1:
