### ISSUE TITLE
Directory created after running all tests successfully

### ISSUE THREAD

**Issue by smtchahal** [pythonindia/junction#445]
After running all tests successfully (`$ py.test`), a directory called `qr_files` gets created at the root of the project, containing a single file named `Pankaj Kumar_TKEFAJC.png`.

Steps to reproduce the bug:

1. Start with a clean working directory and run `py.test`.
2. Make sure the tests are successful.
3. There's a directory named `qr_files` at the root of the project.

Apparently this is done by `tests.unit.tickets.management.commands.test_sync_data`, which calls `junction.tickets.management.commands.sync_data.Command.handle`.

Proposed solutions:

- Add `qr_files` to `.gitignore`.
- Add some sort of clean-up mechanism in the test module that runs after the test is complete, which deletes the directory.

**Comment by theskumar** [comment]
@smtchahal adding `qr_files` to `.gitignore` works, want to submit a PR?

**Comment by smtchahal** [comment]
Done!
