### ISSUE TITLE
Markdown preview isn't working in production

### ISSUE THREAD

**Issue by kracekumar** [pythonindia/junction#458]
Junction uses [django-pagedown](https://github.com/timmyomahony/django-pagedown) for markdown input. In the local environment, comment section displays the preview whereas this is missing in production.

#### Staging screenshot
![screen shot 2016-07-02 at 7 25 04 pm](https://cloud.githubusercontent.com/assets/311929/16540623/ed9b9652-4088-11e6-8e19-db928683178f.png)

#### Production screenshot

![screen shot 2016-07-02 at 7 26 48 pm](https://cloud.githubusercontent.com/assets/311929/16540629/21d5dffe-4089-11e6-8acf-14ee38a801e9.png)

In both the local and production environment div element is available. In the production, there is an extra javascript error.

```
pagedown_init.js:46 Uncaught TypeError: Cannot read property 'init' of undefinedinit @ pagedown_init.js:46init @ pagedown_init.js:60
``` 

@vigneshsarma @theskumar Any idea why this happens ?

**Comment by theskumar** [comment]
the pagedown_init.js doesn't seems to be upto date on server. Here is the diff, local vs prod:
<img width="616" alt="1___tmp_ht__zsh_" src="https://cloud.githubusercontent.com/assets/236356/16540856/8b78eb2a-4090-11e6-8ec3-795fd46d790d.png">

**Comment by theskumar** [comment]
Not sure, why this would have happened though. collectstatic is supposed to overwrite the existing files, right?

**Comment by theskumar** [comment]
well, i've updated the file manually for now. It would be worth looking into why this happened. pagedown version is same on my local and remote machine.

**Comment by theskumar** [comment]
Used `--clear` with collectstatic to get a fresh copy of the file. 

Generally, the files are updated based on timestamps, but i've no clues why this didn't happen for pagedown library.

@vigneshsarma https://docs.djangoproject.com/en/1.9/ref/contrib/staticfiles/#collectstatic has more info.
Do you think it's a good to add `--clear` to https://github.com/pythonindia/magudi/blob/master/salt/roots/lib/env_update.sls#L11

**Comment by vigneshsarma** [comment]
From the docs, it seems like collectstatic itself is supposed to update the files if it has been modified. Not sure why it didn't happen in this case. 

@theskumar `--clear` seems like an option. 

But during the deploy it will cause a short period where the static files will be delete and site might have issues for a short time. This will be a matter of seconds.

If this is acceptable we can add that option.

**Comment by kracekumar** [comment]
No downtime of any asset.

**Comment by kracekumar** [comment]
@ChillarAnand Is it fixed in production ?

**Comment by ChillarAnand** [comment]
I think @theskumar fixed this in production.

**Comment by kracekumar** [comment]
@ChillarAnand You're right.
