### ISSUE TITLE
Home page - UI redesign

### ISSUE THREAD

**Issue by sivaa** [pythonindia/junction#47]

**Comment by kracekumar** [comment]
I think @mudassir0909 fixed. @theskumar Is there anything we need to update ?

**Comment by saurabh-fueled** [comment]
@sivaa @kracekumar The homepage looks good as of now, unless we want to add more widgets/info on it. New separate issue can be created for any added functionality.

**Comment by theskumar** [comment]
@sivaa @kracekumar The homepage looks good as of now, unless we want to add more widgets/info on it. New separate issue can be created for any added functionality.






On Wednesday, Jan 28, 2015 at 10:53 am, Saurabh <notifications@github.com>, wrote:
@sivaa @kracekumar The homepage looks good as of now, unless we want to add more widgets/info on it. New separate issue can be created for any added functionality.
