### ISSUE TITLE
Dashboard needs ability to sort through reviewed/unreviewed proposals.

### ISSUE THREAD

**Issue by akshayaurora** [pythonindia/junction#481]
Dashboard needs ability to sort through reviewed/unreviewed proposals.

**Comment by akshayaurora** [comment]
@kracekumar ^^

**Comment by kracekumar** [comment]
Fixed in #483 #485 #484. 

URLS
-------

- https://in.pycon.org/cfp/<slug>/dashboard/proposal_state/?q=unreviewed
- https://in.pycon.org/cfp/<slug>/dashboard/proposal_state/?q=reviewed
