### ISSUE TITLE
Make all fields readonly after final selection date

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/junction#499]
We should make all fields of proposal readonly after the final selection deadline.
If changed are to be CFP coordinator or admin can do it.

**Comment by kracekumar** [comment]
I'd like to leave the feature as it as. The system captures revision of all the fields in the proposal https://github.com/pythonindia/junction/blob/master/junction/proposals/models.py#L91. Sample URL: https://in.pycon.org/cfp/nimda/proposals/proposal/<proposal_id>/history/<history_id>/
