### ISSUE TITLE
Proposals List/Filters

### ISSUE THREAD

**Issue by sivaa** [pythonindia/junction#5]
The list view of proposal page should have options to filter the proposals by Section (field - `proposal_section`) and Type (field - `proposal_type`)

**Comment by theskumar** [comment]
This has been implemented via the `tag` links in proposal list view. Do we need/want any additional UI for this? If not, can we close this issue @sivaa @kracekumar ?

**Comment by kracekumar** [comment]
Yes we have tags, so this isn't needed.

On Sun, Feb 8, 2015 at 11:01 AM, Saurabh Kumar <notifications@github.com>
wrote:

> This has been implemented via the tag links in proposal list view. Do we
> need/want any additional UI for this? If not, can we close this issue
> @sivaa <https://github.com/sivaa> @kracekumar
> <https://github.com/kracekumar> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pythonindia/junction/issues/5#issuecomment-73397902>.
>



-- 
Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521

**Comment by theskumar** [comment]
awesome! closing this issue now.

**Comment by sivaa** [comment]
@theskumar @kracekumar Yep. But, not sure if all the users know that they can able to click on the tags. It would be nice if we can multi level filter options with the proposal type/section/target audience. I will create a separate issue for this.

**Comment by theskumar** [comment]
cool!
