### ISSUE TITLE
Upgrade to Django 1.9

### ISSUE THREAD

**Issue by ravishanker404** [pythonindia/junction#502]

**Comment by kracekumar** [comment]
Any updates?

**Comment by cosmologist10** [comment]
I am working on this issue.

**Comment by kracekumar** [comment]
@cosmologist10 Thanks for picking up the issue! Please keep us updated about the progress. You may need to add few extra test cases.

**Comment by cosmologist10** [comment]
I have updated the packages and fixed some bugs, still there are some in which i'm really confused. Please have a look:
http://paste.opensuse.org/32513794

**Comment by kracekumar** [comment]
Django 1.10 consolidated  `TEMPLATES_` variables into `TEMPLATES` variable. Junction `common.py` Contains `TEMPLATE_DIRS` which needs to go into `TEMPLATES`. Here is the documentation for help: https://docs.djangoproject.com/en/1.10/topics/templates/

**Comment by cosmologist10** [comment]
I have already added this http://paste.opensuse.org/66070349 and still
getting the same error. Followed this
http://stackoverflow.com/questions/32445953/django-app-works-fine-but-getting-a-template-warning-message
still no effect.

**Comment by kracekumar** [comment]
I had an assumption you're working on `Django 1.10`. If you're doing that, let's first move to Django 1.9. 1.8 to 1.10 migration breaks a lot of base libraries with the current version.  

I made three changes in setting files.
1. Copy your `TEMPLATES` variable.
2. Change  `DEBUG` to `# DEBUG = os.environ.get('DEBUG', 'on') == 'on'` and add `'debug' : DEBUG` in `OPTIONS` under `TEMPLATES`.
3. Comment `TEMPLATE_CONTEXT_PROCESSORS`. 

```
krace@hotbox /m/u/c/junction> pip freeze | grep 'Django'
Django==1.9
krace@hotbox /m/u/c/junction> python manage.py runserver
/home/krace/.virtualenvs/junction2.7/local/lib/python2.7/site-packages/django/contrib/webdesign/__init__.py:11: RemovedInDjango110Warning: django.contrib.webdesign will be removed in Django 1.10. The {% lorem %} tag is now included in the built-in tags.
  RemovedInDjango110Warning

.....
System check identified no issues (0 silenced).
January 11, 2017 - 15:36:55
Django version 1.9, using settings 'settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.


```
Let me know if this works.

**Comment by kracekumar** [comment]
@cosmologist10 Any update on the issue?

**Comment by cosmologist10** [comment]
On 11-Feb-2017 10:06 pm, "R.Kracekumar" <notifications@github.com> wrote:

@cosmologist10 <https://github.com/cosmologist10> Any update on the issue?


Still working on this issue, only one bug left, I think I will make the PR
by the end of this week

You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/pythonindia/junction/issues/502#issuecomment-279157887>,
or mute the thread

**Comment by cosmologist10** [comment]
Hey Krace! I have updated the django version from 1.8 to 1.9 and now i am running the test cases and getting this issue https://paste.ubuntu.com/24216128/ . Any suggestions

**Comment by ananyo2012** [comment]
Current Django version in 1.9. Stale issue. Hence closing.
