### ISSUE TITLE
Comments are not displayed in chronological order

### ISSUE THREAD

**Issue by punchagan** [pythonindia/junction#508]
Noticed this in the reviewer comments section. May or may not be true with public comments.

**Comment by kracekumar** [comment]
In reviewers section latest comment at the bottom. Reversing the order will help?

**Comment by punchagan** [comment]
No, they are not always in that order, either.  They get mixed up. For instance look at reviewer comments on [this page](https://in.pycon.org/cfp/2016/proposals/algorithmic-music-generation~dBrxd/)

**Comment by ChillarAnand** [comment]
Sorry for inconvenience. Will be fixed in  https://github.com/pythonindia/junction/pull/509

**Comment by ChillarAnand** [comment]
Fixed in https://github.com/pythonindia/junction/pull/509. Please reopen if there are any issues.
