### ISSUE TITLE
Update base libraries

### ISSUE THREAD

**Issue by kracekumar** [pythonindia/junction#514]
The libraries in `requirements.txt` are lacking behind the current master. For example, current `all-auth` version is `0.30` but we use `0.21`. Upgrade all the libraries to latest version.

This change may require code changes.

**Comment by palnabarun** [comment]
Current `django-allauth` version is 0.32.0

https://github.com/pythonindia/junction/blob/e9b198e5dbe3841e97bb2e4d5a59d4efc62f8e3b/requirements.txt#L29

We can close this.
