### ISSUE TITLE
Should we participate in RGSOC?

### ISSUE THREAD

**Issue by kracekumar** [pythonindia/junction#515]
[Rails Girls Summer of Code](http://railsgirlssummerofcode.org/blog/2016-12-01-rgsoc-2017-project-submissions-open) is accepting applications for open source projects to participate.

The event is for three months. The participants get involved in any open source project from July 1st to September 30th. The project mentors will help the participants online. This is a solid work for mentors!
Here is a [guideline](http://railsgirlssummerofcode.org/guide/projects/).

Junction definitely needs to get better at all aspects UI/UX, code cleanup, easier deployment etc... We have significant areas to improve.

The question is should we participate? If so we need handful people helping participants. I need multiple helping hands. Please share your opinion and availability.

**Comment by kracekumar** [comment]
Jan 31 is the deadline for application submission.

**Comment by kracekumar** [comment]
@ChillarAnand @vnbang2003 @theskumar @sivaa

**Comment by ChillarAnand** [comment]
Are there any prerequisites for projects? I'll be available to help.

**Comment by vnbang2003** [comment]
+1 👍

**Comment by kracekumar** [comment]
Guidelines: http://railsgirlssummerofcode.org/guide/projects/
Project details: https://teams.railsgirlssummerofcode.org/projects/new

@ChillarAnand. We need to create a list of issues to work.

**Comment by theskumar** [comment]
I won't have bandwidth to take this up. If there are any quick help possible, I would to get involved. 

Cheers,

**Comment by kracekumar** [comment]
I just realised, I forgot to submit the project :-(
