### ISSUE TITLE
manage dev sprint and open space proposals

### ISSUE THREAD

**Issue by bhanuvrat** [pythonindia/junction#525]
Create structure to enable management of Open space and Dev Sprint proposals.

**Comment by kracekumar** [comment]
There are multiple ways to achieve using current settings.

1. Create a new conference Say "PyCon India 2016 Open Space."
2. Add a separate section along with "Workshops," and "Talks." Junction supports closing sections based on time. So when open space is accepting proposal the users can't submit new talks.

Both the approaches allow the user to propose their talks and projects. Other users can comment and carry on the conversation.

The projects can be shortlisted, private, and public conversation is also possible using comment features.

Can you put down specific features or changes in your mind?

**Comment by Ishaan28malik** [comment]
Hey is it still open I want to work on this

**Comment by ananyo2012** [comment]
Devsprints are not like regular CFPs where a Reviewer approves a proposal. It's more like a wiki page. We can have similar wiki page for CFP. #568 discusses this.
