### ISSUE TITLE
Mark public comments as spam

### ISSUE THREAD

**Issue by kracekumar** [pythonindia/junction#529]
Only logged in user is allowed to leave a public comment. Creating an account and post marketing material is non-trivial. Three instances, [first](https://in.pycon.org/cfp/pycon-india-2015/proposals/python-traceback-for-humans~bWnga/#comment-2848), [second](https://in.pycon.org/cfp/pycon-india-2015/proposals/python-traceback-for-humans~bWnga/#comment-2889) and [third](https://in.pycon.org/cfp/pycon-india-2015/proposals/python-traceback-for-humans~bWnga/#comment-2889).  

Add an option to mark as spam by logged in user other than the commenter.

**Comment by satyanash** [comment]
I think this feature has been added as I can only see the comments mentioned above as _The comment is marked as spam._
