### ISSUE TITLE
Proposal Create/Update Page - Proposal section UI Issue 

### ISSUE THREAD

**Issue by sivaa** [pythonindia/junction#53]
![proposal create issue](https://cloud.githubusercontent.com/assets/2163422/5680581/0c223e3a-9835-11e4-945f-26e50434af50.PNG)

**Comment by kracekumar** [comment]
This should be drop down not radio button.

On Fri, Jan 9, 2015 at 7:24 PM, Sivasubramaniam Arunachalam <
notifications@github.com> wrote:

> [image: proposal create issue]
> <https://cloud.githubusercontent.com/assets/2163422/5680581/0c223e3a-9835-11e4-945f-26e50434af50.PNG>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pythonindia/junction/issues/53>.
>



-- 
Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521

**Comment by kracekumar** [comment]
Same as https://github.com/pythonindia/junction/issues/58
