### ISSUE TITLE
Prevent user from posting spam

### ISSUE THREAD

**Issue by kracekumar** [pythonindia/junction#530]
When a user crosses, a threshold for spam marking, disallow user to comment on any public post.

**Comment by kracekumar** [comment]
There are significant spams (posted in public) in the DB by many users. As of now, I'm marking those comments as "The message is blocked as spam and content removed." and deactivate the users. All these users use `gmail, outlook, yahoo` email address.

**Comment by theskumar** [comment]
Do you think some sort of moderation will help?

**Comment by kracekumar** [comment]
Yes. Allow any user to post a comment. After a comment, any logged-in user can mark comment as spam. If the comment exceeds threshold count, mark the content as spam and bar the user from posting future comments.

On a long term, build a system https://github.com/pythonindia/junction/issues/273
