### ISSUE TITLE
Proposal Creation Appears to Fail

### ISSUE THREAD

**Issue by theSage21** [pythonindia/junction#534]
Proposal Creation for PyCon '17 fails. Variations tried:

- Public / Draft as status
- No images in description
- With / without uOrigin blocker turned on.

Same error message seen in all cases.

![image](https://user-images.githubusercontent.com/7693265/27603783-df06cba2-5b94-11e7-9786-868f57a5ac34.png)

 The proposal **DOES** get created as seen in this screenshot, but the error message led me to believe that it was failing.

![image](https://user-images.githubusercontent.com/7693265/27603947-75ab5c26-5b95-11e7-9da2-5a6cec939ac8.png)

However, I don't remember which combination of changes got through and which failed. Server side inquiries should clear that up IMHO.

**Comment by kracekumar** [comment]
Thanks for the report @theSage21. This is because of `redis` service failure  which @vigneshsarma needs to fix. For now, this is fixed by making `USE_ASYNC_FOR_EMAIL=False`
