### ISSUE TITLE
URLs should be autolinked

### ISSUE THREAD

**Issue by anandology** [pythonindia/junction#547]
The markdown format expects urls to be put between `<` and `>` to make them links.  I see lot of speakers adding links to their slides, but the are not hyperlinked. 

Both GitHub and StackOverflow uses a modified version of markdown that autolinks URLs. Junction too should support this extension.

References:

* [GitHub Flavored Markdown](https://github.github.com/gfm/)

**Comment by anandology** [comment]
Here is a sample code that you may be able to adopt for this:

https://github.com/internetarchive/openlibrary/blob/cc3a6ea65081e466866d1908cd54c5cd77ce4fcc/openlibrary/core/olmarkdown.py#L23

**Comment by kracekumar** [comment]
Duplicate of #539.

**Comment by anujaagarwal** [comment]
Hello @anandology , @kracekumar  I want to work on this issue, please can you explain precisely what to do?!

**Comment by ananyo2012** [comment]
Closing this as this is duplicate of #539
