### ISSUE TITLE
"Your Proposals" should be displayed in the reverse cronological order

### ISSUE THREAD

**Issue by anandology** [pythonindia/junction#548]
My profile currently shows my proposals from 2015 on the top and 2017 at the end. It should be in the reverse order.

**Comment by valaparthvi** [comment]
I would like to work on this issue if no one else is working on it.

**Comment by kracekumar** [comment]
@valaparthvi Please go ahead. The relevant code is in https://github.com/pythonindia/junction/blob/master/junction/proposals/dashboard.py

**Comment by satyanash** [comment]
looks like this is implemented in #550

**Comment by kracekumar** [comment]
@satyanash Good catch. 

@valaparthvi Apology. Can you look at some other issue? 

Fixed in https://github.com/pythonindia/junction/pull/550
