### ISSUE TITLE
The parent URL of cfp page should not give 404

### ISSUE THREAD

**Issue by anandology** [pythonindia/junction#558]
The URL of the CFP page for PyCon India 2017 is:

https://in.pycon.org/cfp/2017/proposals/

If you look at one level up, the URL <https://in.pycon.org/cfp/2017> gives `404`. It is generally good practice to make sure the parent either has thing to show or redirect to appropriate page.

In this case, it would be better to redirect to `proposals/` page instead of showing 404.

**Comment by realslimshanky** [comment]
@anandology I'm working on fixing this issue.

**Comment by dishantsethi** [comment]
This issue is still not solved, @anandology can I work on this?

**Comment by zerothabhishek** [comment]
Thanks @dishantsethi.
Since a PR is already raised for this, it will be great if you can help test and verify it.

-Abhishek (2019 coordinator)
