### ISSUE TITLE
stepping down as one of the maintainer

### ISSUE THREAD

**Issue by kracekumar** [pythonindia/junction#559]
For past few years, I was involved in the project and contributed whatever I can. Going forward, I'm not in a position to contribute to the projects. I no more possess time, energy, and my interest over time has drifted. I request members (https://github.com/orgs/pythonindia/teams/pycon-2015-team/members) to take care of the project, and decide about members and not rely on me for any decisions. I'll not be watching the progress of the project as well.

It was fun to work with all you; I had the best time collaborating with all of you and an incredible journey of learning.

**Comment by ananyo2012** [comment]
@palnabarun Maybe we can keep this in the action items of the Technology WG for PyCon 2020 to take up the maintenance and future of the project.

**Comment by palnabarun** [comment]
@ananyo2012 Agreed. I think we should take up maintainership for at least two years, train shadows for the role and then relinquish our duties. This would keep the ball rolling.

If at any point in time, there is a lack of interest, emeritus maintainers can step in.

**Comment by palnabarun** [comment]
This is the method we follow in Kubernetes SIG leadership.

**Comment by ananyo2012** [comment]
Sounds good. We need to improve the documentation so that transfer can happen smoothly.

**Comment by pradyunsg** [comment]
We need to improve a lot of things. 🙈
