### ISSUE TITLE
Feature Request: Review Ratings for Proposals

### ISSUE THREAD

**Issue by jaidevd** [pythonindia/junction#560]
In PyCon India 2018, the review will happen in three stages, the first of which requires reviewers to submit a rating for each proposal, by responding to the following statement:

"This proposal will make a good talk / workshop at PyCon India 2018":
1. Strongly agree
2. Agree
3. Neutral
4. Disagree
5. Strongly Disagree

We need this rating system to be present for each proposal and for each reviewer, and we should be able to save and retrieve all this data. i.e. The rating given by any reviewer for any talk, we should be able to extract it.

**Comment by ananyo2012** [comment]
@jaidevd Should we show the average Rating for the proposal out of 5 ? Also do we need to Show the review of individual reviewers ?

**Comment by ananyo2012** [comment]
So I checked the code and found there is already a Rating system for reviewers. But it is a 4 point Rating system that is scored in this manner
```
-1 - Shouldn't be allowed
0 - Not bad
1 - Good
2 - Must have
```
Are they ok or do you want to rename them as you suggested ?

**Comment by ananyo2012** [comment]
I am not sure how they are displayed though. Will check and report.

**Comment by jaidevd** [comment]
@ananyo2012 We need to get rid of the old rating system, and apply the new one. We need to show the review of individual reviewers, but they should be anonymized. There's no need to show the average.

Hope that helps. Thanks.

**Comment by ananyo2012** [comment]
ok. I think we can reuse the same structure just change the Rating
parameters. It will show the rating of individual reviewers. For
anonymousity junction uses nicknames such as Reviewer1, Reviewer2. That
should be ok right?

**Comment by jaidevd** [comment]
Yes, those nicknames are fine.

**Comment by ananyo2012** [comment]
@jaidevd Here is the screenshot of the Voting page
![screenshot from 2018-07-03 07-41-31](https://user-images.githubusercontent.com/10486343/42195050-a91aa706-7e94-11e8-83b1-e63accb16dd1.png)

Here is the votes dashboard where all Rating will be shown for each proposal
![screenshot from 2018-07-03 07-41-16](https://user-images.githubusercontent.com/10486343/42195071-c7029bf2-7e94-11e8-9912-b80cc94ebe6b.png)

Only the reviewer who has an access to review a specific section can Accept/Reject a proposal.

**Comment by jaidevd** [comment]
Thanks, @ananyo2012, this looks good. Just a few changes.
The voting page should have this line on top:
> Do you think this proposal will make a good addition to PyCon India 2018?

Please also remove the vote values. i.e, we should not be capturing numbers, but we should just be keeping them as enums. Also, please see if you can make the radio buttons horizontal instead of vertical, with strongly disagree to the left and strongly agree to the right.

Also, most importantly, please remove the Accept/Reject proposal. We need that but not at this stage, we should deploy this later.

**Comment by ananyo2012** [comment]
@jaidevd Does this look good now? I am not so good at design. I can ask someone from the Design team to design interactive buttons if you want

![screenshot from 2018-07-03 23-23-34](https://user-images.githubusercontent.com/10486343/42236443-796b07b0-7f18-11e8-88bd-0fe9ce425a3a.png)
![screenshot from 2018-07-03 23-23-05](https://user-images.githubusercontent.com/10486343/42236449-7e521fe8-7f18-11e8-8060-6c52056b470a.png)

**Comment by jaidevd** [comment]
@ananyo2012 This looks good, thanks. Sure, the design team can look at this parallelly, but let's not let that block this. Please go ahead an merge this if everything else is fine.
