### ISSUE TITLE
Remove Docker support?

### ISSUE THREAD

**Issue by pradyunsg** [pythonindia/junction#578]
Coming from #517 and a short discussion with @zerothabhishek, ISTM that the docker files are not used in production or in development.

Is anyone willing to update and maintain the docker environment going forward? If yes, then should we move the production deployment to use docker?

In case there's no one willing to step up to do the above in ~15 days or so, I suggest we remove docker related files, to avoid having bit-rotted files in the repository.

/cc @rekenerd @theskumar @bhanuvrat

**Comment by zerothabhishek** [comment]
@ananyo2012 @vigneshsarma your opinions too please.

**Comment by vigneshsarma** [comment]
The reason we added the Dockerfile was #124 . 

Does anyone use it for that purpose?

With just a single server for production, I dont think there is much advantage to using docker in production.

**Comment by ananyo2012** [comment]
I personally use manage.py script to run server locally. But its good to have docker available since its easy for first time setup that works across different OS. Maybe you can move it to a separate branch  and link it to #517 ?

**Comment by pradyunsg** [comment]
> But its good to have docker available since its easy for first time setup that works across different OS.

If it's not being actively maintained or used, I think it's better to remove it. There's been at least 2 instances of contributors trying to use it and failing to do so. (myself and one other)

**Comment by zerothabhishek** [comment]
I think its okay to move it to a branch. Docker is a good idea but for now it seems like an obstacle for new-comers. May be in future we'd distribut an image that can be used directly.

**Comment by palnabarun** [comment]
Hi everyone,

I would be more than happy to maintain the docker setup for junction.

I saw the `Dockerfile` and `docker-compose.yml` in the repository. Since, they were written 4 years ago, they need some oiling. Like for the `Dockerfile`, using `ubuntu:14.04` image unnecessarily increases the size. I tried with `python:2.7` for now and the web container worked, barring other issues.

Let me know what do you think.

**Comment by zerothabhishek** [comment]
Thanks @palnabarun that will be great. Please go ahead with it. 
Docker is not in use on production right now, so we can best use it for development. A smaller sized image would be ideal.

**Comment by sameer1001** [comment]
I tried running the **docker-compose up** today. It doesn't work. It fails with many dependency problems like 

"ERROR: Cannot uninstall 'six'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall."

@palnabarun has any work happened on this yet? If not, let's collaborate and take it forward.

**Comment by pradyunsg** [comment]
In #622, I propose removing the current files; until someone actually puts in the time and effort to get a working on making the setup work -- which would anyway involve rewriting parts of the configuration.

**Comment by ananyo2012** [comment]
#622 closes this
