### ISSUE TITLE
Stored XSS in text fields

### ISSUE THREAD

**Issue by icyphox** [pythonindia/junction#583]
There’s a stored XSS bug in the comments section under each proposal, allowing the attacker to run malicious JS on the client.

## Steps to reproduce
1. Hit "add a comment", found under any proposal
2. Enter `<script>alert(1)</script>` in the text field
3. An alert-box should pop up with `1` in it

## Relevant screenshot
![image](https://user-images.githubusercontent.com/17672379/56045839-9c799200-5d5f-11e9-81f3-2b289762293d.png)

This was tested on the latest commit (https://github.com/pythonindia/junction/commit/d3744d4522bbb31cc03af79b44c6ac408d9090ab) on a local development server. 

**Note**: I haven't tested this on production.

**Comment by zerothabhishek** [comment]
Thanks for reporting this @icyphox

**Comment by zerothabhishek** [comment]
Tested on staging server (junction.h65.in), problem exists

**Comment by icyphox** [comment]
Am I permitted to test on that URL as well? I'm having some issues with the local setup.

**Comment by zerothabhishek** [comment]
Sure go ahead @icyphox

**Comment by zerothabhishek** [comment]
Possible cause: the `markdown` filter used in views allows malicious JS to pass. A better way seems to be to use `markdown_safe` instead.  Another possible technique is to use `markdown|safe|striptags` filters.

**Comment by zerothabhishek** [comment]
Hey @icyphox could you please help us with testing the fix at #587 ? 
Staging: junction.h65.in

**Comment by icyphox** [comment]
I'm away from my computer at the moment, I'll do this tomorrow. 

Bear with me :)

**Comment by icyphox** [comment]
@zerothabhishek I'm having trouble logging in on the staging server. GitHub OAuth doesn't seem to work nor does the email confirmation when I try to login via email.

**Comment by zerothabhishek** [comment]
@icyphox yeah emails are not working on that server (OAuth has also not been setup). You can perhaps use the admin to  mark the account as verified. Sending credentials via email

**Comment by icyphox** [comment]
Looks good from my end. Input appears to be sanitized server-side as well. Great!

**Comment by zerothabhishek** [comment]
Thanks @icyphox
