### ISSUE TITLE
Upgrade to Python 3.7

### ISSUE THREAD

**Issue by zerothabhishek** [pythonindia/junction#586]
An effort has already been made for this (#316), but the production still runs Python 2.7

We need to make sure that -
- Python version is the latest (3.7)
- Production gets updated (change scripts in magudi)
- Documentation is updated to reflect that
- Dockerfile is also updated

And also,
- All tests should pass
- All the functionality should be working

**Comment by palnabarun** [comment]
I was going to point this out, as Python 2.7 support ends on `1st January 2020`.

Is there any plan on how this is going to be spec'ed out?

**Comment by ananyo2012** [comment]
#614 tracks this now. Hence closing this.
