### ISSUE TITLE
Comment submission is slow

### ISSUE THREAD

**Issue by zerothabhishek** [pythonindia/junction#588]
Perhaps because it tries sending emails then and there - which can be done asynchronously.

**Comment by theSage21** [comment]
- I thought this was already happening? [https://github.com/pythonindia/junction/blob/master/junction/proposals/comments_views.py#L52]
-  It seems to be explicitly turned off if I'm not wrong [https://github.com/pythonindia/junction/blob/master/settings/common.py#L248]

**Comment by zerothabhishek** [comment]
@theSage21 Thanks for the comment. You're right it has been explicitly disabled - something I noticed much after raising this issue. I suppose that makes the job easier now.
