### ISSUE TITLE
grammatical error status of the talk statement

### ISSUE THREAD

**Issue by dishantsethi** [pythonindia/junction#598]

**Comment by dishantsethi** [comment]
![Screenshot from 2019-06-24 16-37-38](https://user-images.githubusercontent.com/31399916/60014484-c96eed00-969e-11e9-83ff-14cca6cb194a.png)
It should be `can't see the` , instead of 'can't the see the'

**Comment by deepscbe** [comment]
Thanks for notifying, I'll correct it.

**Comment by dishantsethi** [comment]
This issue is solved. Should I delete this one or it will be closed by the maintainers @deepscbe  ?
