### ISSUE TITLE
Incorrect link to conference having different slug in profile dashboard

### ISSUE THREAD

**Issue by deepscbe** [pythonindia/junction#604]
After logging in, and click on "My Proposals", there is a link to go back to talks "Talks 2019" which is redirecting to wrong URL.

![image](https://user-images.githubusercontent.com/38253214/60656300-d80e8e80-9e6c-11e9-8e80-2f13612441a7.png)
![image](https://user-images.githubusercontent.com/38253214/60656329-df359c80-9e6c-11e9-9c30-1db6aa7f4c38.png)

**Comment by dishantsethi** [comment]
I want to work on this issue.

**Comment by dishantsethi** [comment]
Hey, I can't find the link to go back to "Talk 2019" after clicking on "My proposals". @deepscbe 
![Screenshot from 2019-07-06 14-18-02](https://user-images.githubusercontent.com/31399916/60754048-47b18480-9ff9-11e9-849c-0773b02c0c93.png)

**Comment by deepscbe** [comment]
I've already committed the fix and Abhishek is verifying the same.

**Comment by ananyo2012** [comment]
@deepscbe I don't see the PR for this issue. So this is still open.
