### ISSUE TITLE
Drop Python 2 support + update primary deployment to Python 3

### ISSUE THREAD

**Issue by kracekumar** [pythonindia/junction#614]
Previously Junction worked on Python 2 and Python 3 but deployed only in python 2 in server. From now use only Python 3 in server and remove support for Python 2 and update requirements.

- [x] Drop Python 2 support and enable Python 3 support.
- [ ] Migrate server to Python 3(magudi).
- [x] Upgrade packages and refactor the code.
- [ ] Deploy to the server.
- [ ] Update any relevant documentation

**Comment by ananyo2012** [comment]
I think #622 addresses the CI tests for this. The original PR #615 made by Krace checks for py 3.6 and 3.7 as well. @pradyunsg What do you think regarding supporting those versions ?

**Comment by pradyunsg** [comment]
I'm on board for being Python 3.5+ compatible.

I do think it'd be a good idea to stick to a single Python version though, and 3.8 is a good target as of today.

**Comment by ananyo2012** [comment]
@palnabarun Please close this issue once the prod migration to Python 3 is done

**Comment by inovizz** [comment]
What is the current state of this issue? Is there anything I can help here?

**Comment by pradyunsg** [comment]
No movement since Jun, I think.

https://github.com/pythonindia/junction/pull/686
https://github.com/pythonindia/junction/pull/687
https://github.com/pythonindia/junction/pull/667

These seem relevant, though I imagine there's more stuff. :)

**Comment by ananyo2012** [comment]
Junction upgrade to Django 3.2 and python 3.10 is complete. Thanks to all who contributed in this huge task.
