### ISSUE TITLE
Configure Read The Docs integration

### ISSUE THREAD

**Issue by palnabarun** [pythonindia/junction#626]
I have secured https://in-junction.rtfd.io for hosting the junction documentation. The configuration needs to be done to build and serve documentation for `docs/`.

PS: I will be taking care of this issue.

**Comment by ananyo2012** [comment]
@palnabarun Have you checked https://pythonindia.github.io/junction/ . The previous documentation used mkdocs. Can't we have something similar for Sphinx as well instead of moving to rtfd domain ?

**Comment by ananyo2012** [comment]
#43 discusses the mkdocs setup

**Comment by palnabarun** [comment]
You can always `make html` the sphinx docs and deploy. But, then it would require unnecessary hacks and managing `gh-pages` branch out of sync with the master tree.

Bdw, what are the cons of hosting at RTD?

**Comment by pradyunsg** [comment]
> Bdw, what are the cons of hosting at RTD?

One more service to handle auth / permissions for. :)

> You can always make html the sphinx docs and deploy.

Or... let a GitHub Action do that for you.

**Comment by palnabarun** [comment]
RTD doesn't require credential handling. One time process to create the site. And I can add as many maintainers as needed and keep the ball rolling.

I like the GH Action idea though.

**Comment by ananyo2012** [comment]
Yes let's push to gh-pages on update to docs folder in master using GitHub Action

**Comment by pradyunsg** [comment]
Alright, I think there's concensus for GA. Let's close this then.
