### ISSUE TITLE
Suggest contributors to create PRs for different branches

### ISSUE THREAD

**Issue by pradyunsg** [pythonindia/junction#628]
Should we also mention that `you should always create a new branch for a new pr to avoid conflicts`?

_Originally posted by @sks444 in https://github.com/pythonindia/junction/pull/621_

Yes, we should. It's a little tricky to phrase though, so filing an issue to follow up on this suggestion.

**Comment by palnabarun** [comment]
**It should be there in the documentation if it is not there now. It is standard practice.**

**Comment by sks444** [comment]
I could take this up.

**Comment by palnabarun** [comment]
@sks444 Feel free to file a PR! :)

Assigning you.
