### ISSUE TITLE
On new talk submission email need to send to panel members

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/junction#64]
We need to enable sending email on panel members for each talk submitted.
Email should contains Title, Category,  Link , Author bio info.

**Comment by bhanuvrat** [comment]
emails are to be sent synchronously? I don't see celery / gevent around.

**Comment by sivaa** [comment]
@bhanuvrat Yes. At this moment. It would be nice you if you can add the async support for this(if you have some bandwidth).

**Comment by bhanuvrat** [comment]
@sivaa okay. let me see.

**Comment by bhanuvrat** [comment]
celery would be fine?
