### ISSUE TITLE
Add CI for building documentation

### ISSUE THREAD

**Issue by pradyunsg** [pythonindia/junction#644]
Because, that's important?

**Comment by palnabarun** [comment]
The PR's already go through the Travis.

**Comment by palnabarun** [comment]
I am working on the documentation part.

**Comment by palnabarun** [comment]
As a side note, please put complete descriptions when filing issues. :)

**Comment by pradyunsg** [comment]
> As a side note, please put complete descriptions when filing issues. :)

I thought the title was fairly self-explanatory. None the less, fair point. I'll be more elaborate in the future.
