### ISSUE TITLE
Fix deprecation warnings, related to use of older APIs

### ISSUE THREAD

**Issue by sameer1001** [pythonindia/junction#652]
Not an exhaustive list, but here are some of the warnings that are coming while building the test. 
https://gist.github.com/pradyunsg/0d3cfefe1f184f7c7001e85ba5ecb8be

We can take care of these by making small changes overall I guess. 

I would like take this, will work on it gradually and update progress here.

**Comment by ananyo2012** [comment]
I think it will be good if you can mention the reasons that are causing the warnings and proceed with the fixes.

**Comment by sks444** [comment]
Hi @sameer1001, please note that there are two prs already fixing some of the warnings: https://github.com/pythonindia/junction/pull/643, https://github.com/pythonindia/junction/pull/653

Make sure the changes you're doing doesn't overlap, otherwise it will be repetitive work. :)
