### ISSUE TITLE
Dockerize Junction and related components

### ISSUE THREAD

**Issue by palnabarun** [pythonindia/junction#680]
Services to be run
---
1. Postgres 12
2. Redis 6
3. Web application on Python 3
4. Celery workers on Python 3

Additional system-wide config
---
1. Nginx rule to reverse proxy traffic to the containers
2. Co-ordinate config management for production

Follow Up
---
- [ ] Remove Python 2.7 from CI
- [ ] Remove other sunsetted Python versions from support (if any)
- [ ] Upgrade to Django 2.2 LTS and fix all dependency issues (#684)

**Comment by onlinejudge95** [comment]
I can take it if it helps ease the burden.

**Comment by palnabarun** [comment]
@onlinejudge95 -- Thanks for the help! You can get started with the port to Django 2.2 LTS.

There will some major breaking changes though. Please feel free to create a new umbrella for tracking the work.

**Comment by onlinejudge95** [comment]
Will raise a PR by weekend

**Comment by onlinejudge95** [comment]
@palnabarun meanwhile can you provide clarity on `Remove other sunsetted Python versions from support (if any)`. This can go independent(to some extent, corner cases being the dependencies in this project having a hard limit) just like 2.7 one

**Comment by palnabarun** [comment]
> meanwhile can you provide clarity on Remove other sunsetted Python versions from support (if any).

By that I mean 3.5 is going to be EOL on 2020-09-13, IIRC. We should target 3.6+ for CI and production.

> As far as upgrade goes I will be removing the Draft PR and starting from scratch. WIll ping about the same in the issue #684

Sure.

**Comment by pradyunsg** [comment]
TBH, given that there's only 1 deployment that we know of, it might be a good idea to to push for 3.8+ compatibility.

**Comment by ananyo2012** [comment]
This is complete now.
