### ISSUE TITLE
Django version bump

### ISSUE THREAD

**Issue by onlinejudge95** [pythonindia/junction#684]
- [ ] Update Django version to next minor release i.e. `1.10`
    1. Blocked on `django-uuidfield` dependency which is breaking in `Django==1.10`

**Comment by palnabarun** [comment]
@onlinejudge95 -- Can you please write a task checklist for the work needed?

**Comment by ananyo2012** [comment]
There is already issue #611 for this. Please use it to update the status. Individual PRs can track progress of each task in checklist.
