### ISSUE TITLE
[Setup] Error while installing npm packages

### ISSUE THREAD

**Issue by miphilomath** [pythonindia/junction#693]
I have been following the updated documentation on how to [get started](https://in-junction.readthedocs.io/en/latest/development/getting-started.html#initial-setup) with the development of the project and set up the database migrations. For my local setup, I am using virtualenv for python3.5

To set up the frontend of the project, I exected, `npm install` and encountered the following error message.

```
npm WARN deprecated nodeunit@0.9.5: you are strongly encouraged to use other testing options
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
...
...
npm WARN deprecated coffee-script@1.3.3: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
[  ................] - fetchMetadata: sill pacote range manifest for is-property@^1.0.2 fetched innpm ERR! code 1
npm ERR! Command failed: git checkout 1.9.1 - 3
npm ERR! error: pathspec '1.9.1 - 3' did not match any file(s) known to git
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/philo/.npm/_logs/2020-06-09T18_19_14_093Z-debug.log
```

I landed on [this](https://stackoverflow.com/questions/5989592/git-cannot-checkout-branch-error-pathspec-did-not-match-any-files-kn) stackoverflow page for the solution and the problem seems to be related to git but I am unable to resolve the issue. 

I have two git remotes, origin pointing to my fork and upstream pointing to the project git repository.

```
$ git branch -a
  master
  remotes/origin/HEAD -> origin/master
  remotes/origin/add-commit-guidelines
  remotes/origin/develop
  remotes/origin/django-2.2
  remotes/origin/gh-pages
  remotes/origin/github-actions-support
  remotes/origin/master
  remotes/origin/order-proposals
  remotes/origin/sentry
  remotes/upstream/add-commit-guidelines
  remotes/upstream/develop
  remotes/upstream/django-2.2
  remotes/upstream/gh-pages
  remotes/upstream/github-actions-support
  remotes/upstream/master
  remotes/upstream/order-proposals
  remotes/upstream/sentry
```

Can someone please help me on resolving the issue?

**Comment by ananyo2012** [comment]
Please try doing a yarn install. We have moved to yarn for static assets.
Will update the readme shortly

**Comment by miphilomath** [comment]
Thanks @ananyo2012. It worked.
