### ISSUE TITLE
Proposals need to be ordered by most recent timestamp

### ISSUE THREAD

**Issue by ananyo2012** [pythonindia/junction#706]
The CFP page at https://in.pycon.org/cfp/2020/proposals/ need to ordered by most recent timestamp. This needs to be tested with the Production version of Database used, since order of posts differ across databases. The production DB uses Postgres 9.6

**Comment by palnabarun** [comment]
>  This needs to be tested with the Production version of Database used, since order of posts differ across databases.

What is the basis of the above inference that "order of posts differ across databases"? Are you trying to say it is yet to be tested? It looks like an inference from the statement.

**Comment by ananyo2012** [comment]
What I meant is the Dev setup uses sqlite so the order seen by using sqlite
may differ when the app is used with postgres.

**Comment by ananyo2012** [comment]
To be specific I was referring to this issue
https://code.djangoproject.com/ticket/19726 . I encountered a similar
situation while working on a separate issue. But I think this should not
effect the timestamp ordering.

**Comment by gutsytechster** [comment]
@ananyo2012 Do you mean that the latest proposal should appear on the top irrespective of votes it has got?

**Comment by ananyo2012** [comment]
Yes the most recent proposal should appear at the top

**Comment by mrxsunil** [comment]
Hi Guys, is anyone currently working on this issue?

**Comment by ananyo2012** [comment]
Closing this as current timestamp order is fine.
