### ISSUE TITLE
Add first time speaker checkbox field in cfp form

### ISSUE THREAD

**Issue by anistark** [pythonindia/junction#707]
Reason: First time speakers can be identified easily and provided required mentorship for.

**Comment by Sc0rpi0n101** [comment]
Hi, I'd like to help with this. 

Can someone tell me where should I update this, or it might take me some time to find it as I've not been through the codebase, and it's relatively large?

**Comment by sayanchowdhury** [comment]
@Sc0rpi0n101 Sure, this should be an easy fix. You can start with setting up the codebase, and then refer these PR #668 #698 #699 

Instead of a CharField you would need to use the BooleanField.

**Comment by abhishekmishragithub** [comment]
I am already working on this.

**Comment by Sc0rpi0n101** [comment]
Ohh, okay then.

**Comment by abhishekmishragithub** [comment]
Fixed in #710
