### ISSUE TITLE
Page Not Found while opening Dashboard

### ISSUE THREAD

**Issue by Bhupesh-V** [pythonindia/junction#709]
### How to reproduce
1. Sign up at junction through GitHub.
2. Click on Username once logged In.
3. Click on Profile.
4. Now click on _Dashboard_ (**In navigation panel, on the left side**).
5. Demo below
![bug](https://user-images.githubusercontent.com/34342551/86584530-a5790380-bfa2-11ea-8e1d-3e16769d1068.png)

### Expected Behaviour
Currently the Dashboard link points to : [https://in.pycon.org/cfp/profiles/edit/user-proposals-list]().
Instead it should (or may) point to [https://in.pycon.org/cfp/profiles/]()

**Comment by ananyo2012** [comment]
Can you mention how did you end up at this link ? For me clicking Dashboard page pointed me to https://in.pycon.org/cfp/profiles/

**Comment by gutsytechster** [comment]
I can reproduce it. According to the steps provided in the issue description, I ended up on the same page.

**Comment by palnabarun** [comment]
Are you sure about this? I couldn't reproduce it either locally or on `in.pycon.org/cfp`.

**Comment by Bhupesh-V** [comment]
> in.pycon.org/cfp

Yes
Once you open your "Edit Profile" option. Click on the Dashboard link

![fix](https://user-images.githubusercontent.com/34342551/89096232-be82a200-d3f2-11ea-88a4-686f7a1ac90f.png)
