### ISSUE TITLE
Page Not Found while clicking on "PyCon India 2020"

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [pythonindia/junction#711]
When i click on this

![junction_error_1](https://user-images.githubusercontent.com/22630684/87096829-be104480-c254-11ea-8729-201b1975387f.png)

i get 

![junction_error_2](https://user-images.githubusercontent.com/22630684/87096823-bbadea80-c254-11ea-84a0-63cdfca6e6a6.png)

**Comment by Sc0rpi0n101** [comment]
This should redirect to https://in.pycon.org/cfp/ instead of where it is redirecting now.

**Comment by gutsytechster** [comment]
On investigation, I found that it happens because here https://github.com/pythonindia/junction/blob/master/junction/urls.py#L147, the URL is suffixed with `--`. I think this is accidental.
I'd be happy to create a PR to resolve this. :)
