### ISSUE TITLE
Proposals page still shows "Accepting Proposals"

### ISSUE THREAD

**Issue by animenon** [pythonindia/junction#725]
The [proposals page](https://in.pycon.org/cfp/2020/proposals/) still shows "accepting proposals".

Snip from the page:

![image](https://user-images.githubusercontent.com/6907950/91524599-38884700-e91d-11ea-9aa9-eccfad2eea3e.png)

Last date for submission was 20th Aug.

**Comment by bkamapantula** [comment]
the page now reflects the deadline as _31 aug_.
