### ISSUE TITLE
Add docker setup for Junction

### ISSUE THREAD

**Issue by inovizz** [pythonindia/junction#750]
- containerize the whole app for faster setup
- setup db, web, celery and redis services
- fix things w.r.t. docker and add basic documentation

**Comment by anuj0456** [comment]
please let me know if any help is required.

**Comment by inovizz** [comment]
> please let me know if any help is required.

This issue is almost sorted with #749 , please feel free to review the PR.

**Comment by ananyo2012** [comment]
@miphilomath reported this issue

On attempting to login via home page, I am getting the following error. 
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/26297035/233629970-6701b98c-ffac-4ecc-80a4-b19eef79bff9.png">

Though If I login through admin site first, I am logged into the application with no error. 

Is anyone else facing similar problem?

**Comment by ananyo2012** [comment]
@miphilomath How are you logging in to junction ? Using some oauth signup or simple email login ? Since you need to setup the smtp provider/oauth in order to use both. Also the full trace from which the error originated would be helpful.

**Comment by miphilomath** [comment]
> @miphilomath How are you logging in to junction ? Using some oauth signup or simple email login ? Since you need to setup the smtp provider/oauth in order to use both. Also the full trace from which the error originated would be helpful.

I created the user using `./manage.py createsuperuser` and used that user to login into the application via homepage.

**Comment by ananyo2012** [comment]
Ok seems to be an edge case. Can be tricky to reproduce. Can you open an issue describing the case when this occurs ?

**Comment by miphilomath** [comment]
I have created a new issue to track this better and reducing noise on this PR.

**Comment by inovizz** [comment]
Please create a separate issue for any bugs, I'll close this issue for now.
