### ISSUE TITLE
Update the docs post junction upgrade and docker setup

### ISSUE THREAD

**Issue by inovizz** [pythonindia/junction#753]
The upgraded version of the junction with Python 3.10 and Django 3.2 is available here at the branch - `feature/upgrade-junction`

Additionally, there is an effort going on to dockerize junction #749, though it only covers basic docker setup, and doesn't update the docs at large or nether contain updated local development steps. So we need to update all of these in the repo and ensure that README, docs, contribution guidelines and local setups are all updated.

**Comment by RajatRajdeep** [comment]
I'm working on this.

**Comment by RajatRajdeep** [comment]
I have raised a following PR for this: https://github.com/pythonindia/junction/pull/761

**Comment by ananyo2012** [comment]
Fixed in #757
