### ISSUE TITLE
Do functional and end to end testing of Junction Upgrade

### ISSUE THREAD

**Issue by inovizz** [pythonindia/junction#754]
We need to test the branch thoroughly from functional and integration perspectives well. We'd appreciate it if someone could add some automation tests to run some scenarios but for now, the priority is to test Junction end-to-end locally and report in case of issues. If you find scenarios working perfectly, you could post a screenshot here.

The community here, who might have used Junction earlier could post a few scenarios to start with.

Branch to test - `feature/upgrade-junction`

**Comment by ananyo2012** [comment]
@soumendrak Thanks for doing CFP testing. This can be closed now.
