### ISSUE TITLE
Review project setup steps and resolve "This page isn't working" error in browser.

### ISSUE THREAD

**Issue by RajatRajdeep** [pythonindia/junction#760]
Hi everyone,

I'm having some trouble setting up the project using docker on my local machine. I need your help in reviewing the junction project setup steps. I performed following steps and the application is running but I am not able to view the app in the browser. The browser shows me **This page isn’t working** error. Please check the attached screenshot.

I have followed following steps:
1. Copy .env.sample and paste it as .env file: cp .env.sample .env
2. Create a “settings” file for local development with Django.: cp settings/dev.py.sample settings/dev.py
3. Build junction_local image using following command: docker build -t junction_local .
4. Run the command "docker-compose up" to start the project.

All the containers are running and I am not seeing any issues on the terminal(in logs) as well. I can also see the dbsqlite file in the container. I think I have missed something here, Please respond if you're aware of the cause of this.

I'm not sure what's causing the issue, but I suspect it might be related to the setup process. I would appreciate it if someone could review the setup steps and let me know if I missed anything or if there's anything else I need to do.

Also, if anyone has encountered a similar issue and knows how to resolve it, I would really appreciate any help or guidance.

<img width="1440" alt="junction-issue" src="https://user-images.githubusercontent.com/46029666/235981289-9989c9fd-e598-4a4d-9b06-6df2eca3394a.png">

**Comment by leshravnya** [comment]
The web server runs on a secure channel. Therefore, you need to use `https` instead of `http`. Use this link https://localhost:8888. It should work for you.

**Comment by RajatRajdeep** [comment]
Understood. Thanks @leshravnya!
The application is accessible at https://localhost:8888.
