### ISSUE TITLE
Error while adding a comment 

### ISSUE THREAD

**Issue by bhansa** [pythonindia/junction#762]
Example URL: https://in.pycon.org/cfp/test-conference/proposals/comment/test-test-test-test-test-test-test-test-test-test-test/create/

Error screen:
![image](https://user-images.githubusercontent.com/9723884/236249705-0091300e-cd98-4716-b08c-430acc4f6cef.png)

**Comment by ananyo2012** [comment]
Thanks for reporting this. This is what I did to fix the issue:

1. Set master role to redis DB 
  ```
  docker-compose exec redis /bin/sh
  # redis-cli
  127.0.0.1:6379>slaveof no one
  ```
  Ref: https://stackoverflow.com/questions/42810115/redis-sentinel-not-connect-to-master-error-readonly-you-cant-write-against-a

2. Rebuild container and redeploy

**Comment by ananyo2012** [comment]
If this issue still persists we need to secure redis with a password and update the redis broker url

**Comment by ananyo2012** [comment]
Applied the above fix in this commit - https://github.com/pythonindia/junction/commit/9948041b3f53d7d45e618df8ac0f9c175e822683
