### ISSUE TITLE
Show username in Junction

### ISSUE THREAD

**Issue by soumendrak** [pythonindia/junction#769]
![Image](https://github.com/pythonindia/junction/assets/10120538/366b109d-cc4c-4142-a3e9-2b7cb1889a58)

- Currently, signed-in users need help seeing their username in Junction. 
- Therefore, it becomes difficult to find that user's username and add Reviewer access without their username. 
- Please add a feature to show the username in the Junction profile page for the signed-in user.

Note: This is for the users who signed in in one of the previous editions and forgot their username.

**Comment by RajatRajdeep** [comment]
I'm working on this.

**Comment by RajatRajdeep** [comment]
Hello, @soumendrak, Is there a particular spot on the profile page where you would prefer the username to be displayed?
I have attached a screenshot for your reference, which shows how we are showing both the full name and username of the proposal author.
<img width="1248" alt="image" src="https://github.com/pythonindia/junction/assets/46029666/918efcbc-43b3-4e4d-a253-4aba4ec54e00">

**Comment by ananyo2012** [comment]
You can put it in https://in.pycon.org/cfp/profiles/edit/ page

**Comment by RajatRajdeep** [comment]
Thanks @ananyo2012, for providing the location.
I have added the username field in Edit Profile Form UI as disabled field. Here's the PR: https://github.com/pythonindia/junction/pull/771

Please check the attached Screenshot and let me know if it looks good.
<img width="1272" alt="image" src="https://github.com/pythonindia/junction/assets/46029666/567bdc74-8779-4165-a37c-22c2f175fc1e">
