### ISSUE TITLE
Error while exporting Review votes

### ISSUE THREAD

**Issue by soumendrak** [pythonindia/junction#772]
Getting errors while exporting Reviewer votes. I have admin access.

I've attached the error reproduction video.
Link of error: [https://in.pycon.org/cfp/pycon-india-2023/dashboard/votes/export/](https://in.pycon.org/cfp/pycon-india-2023/dashboard/votes/export/)

https://github.com/pythonindia/junction/assets/10120538/aefb61c0-4dda-4d7e-82b1-4b34f20223c6

**Comment by ananyo2012** [comment]
Fixed. There was an invalid character in Proposal Section name causing issues in excel sheet name.
