### ISSUE TITLE
Proposal creation page doesn't seem to show proposal type & proposal-section drop-down

### ISSUE THREAD

**Issue by pythonhacker** [pythonindia/junction#87]
Do I need to create this data first in the DB ?  Can we create default data for this in DB ?

![screenshot-create proposal junction - mozilla firefox-1](https://cloud.githubusercontent.com/assets/316177/5932740/eace71e6-a6d9-11e4-842e-454e6e30b502.png)

Caveat: New to junction :)

**Comment by pythonhacker** [comment]
Ok, figured I need to add this in Proposal types and Proposal sections via admin. However still would be nice to have "Workshops" and "Talks" as standard types in DB. Also nice to modify UI to say "You need to associate a proposal type" instead of showing blank.

**Comment by pythonhacker** [comment]
This is not very important, can wait.

**Comment by kracekumar** [comment]
`./manage.py sample_data` should produce it, The  code is here https://github.com/pythonindia/junction/blob/master/junction/conferences/management/commands/sample_data.py

**Comment by kracekumar** [comment]
+1 for UI message.

**Comment by kracekumar** [comment]
The setup section carries instruction to set up sample data.
