### ISSUE TITLE
Should be possible to associate a proposal to multiple sections

### ISSUE THREAD

**Issue by pythonhacker** [pythonindia/junction#88]
The junction@pybelagaum shows a list drop-down, the latest github code shows a group of radio buttons. Neither allows to map one talk to > 1 section.

Can be fixed by making the proposal<->section relation a many-to-many mapping.

**Comment by kracekumar** [comment]
There are cases where a talk can fall into more than one section. In general, it is advised to select the most relevant section. 

For example, `Migrating Django code base to Python 3` will fall into `Python 3`, `Web Development`.  If the talk focuses on `migration of Python 3` the apt section will be `Python 3`. As a result this will help the reviewer/participant to understand what this talk will predominately focus on.

One more way to see this is to have a one primary section to the session and allow two secondary sections. We need to limit the number of sections getting tagged.

**Comment by pythonhacker** [comment]
We've already had quite a few submissions. If you haven't heard from any of the proposers about such a feature, I would think this is redundant. In that case close this.

**Comment by kracekumar** [comment]
We haven't heard anything from other reviewers. I will skip it for now and add in later stage.
