### ISSUE TITLE
Don't display the E-Mail address of the commenter.

### ISSUE THREAD

**Issue by sivaa** [pythonindia/junction#89]
![image](https://cloud.githubusercontent.com/assets/2163422/5933846/26566cf2-a6ec-11e4-97cf-edcd6571a200.png)

http://junction.pybelgaum.org/pybelgaum/proposals/python-for-generating-network-anomalies/

**Comment by kracekumar** [comment]
This should be top priority.

**Comment by vnbang2003** [comment]
We should not be display anyone contact information (Proposer, reviewer and commenter)

**Comment by ChillarAnand** [comment]
looks like it is his username not mail?

**Comment by kracekumar** [comment]
Yes. Just checked that, he updated the name.

On Wed, Jan 28, 2015 at 8:50 PM, Anand Reddy Pandikunta <
notifications@github.com> wrote:

> looks like it is his username not mail?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pythonindia/junction/issues/89#issuecomment-71851786>.
>



-- 
Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521
