### ISSUE TITLE
Proposals - Voting for Comments

### ISSUE THREAD

**Issue by sivaa** [pythonindia/junction#9]
- Each comment on the detailed view of the proposal page should have up/down vote buttons
- The vote count should be displayed between up and down buttons
- Only authenticated user can vote for a comments
- A `ProposalCommentVote` record should be created when an user votes for the a specific comment.
- If the user changes the vote later for the same comment, the existing record should be updated(Ex: Up vote -> Down vote)
- The request should be sent through AJAX.

**Comment by NabeelValapra** [comment]
I'm Working on this. If any one like to join me please look at my fork :)

**Comment by kracekumar** [comment]
Any updates ?

**Comment by NabeelValapra** [comment]
This is done. But not with ajax.

**Comment by kracekumar** [comment]
We can live with this for v1, ajax can wait till next version. Closing this for now.
