### ISSUE TITLE
Proposal Detail - Too much white-space?

### ISSUE THREAD

**Issue by sivaa** [pythonindia/junction#93]
![image](https://cloud.githubusercontent.com/assets/2163422/5933931/85c70cfe-a6ed-11e4-9b24-22c56f2fa796.png)

**Comment by geetanjaligg** [comment]
![screenshot from 2015-01-29 13 13 23](https://cloud.githubusercontent.com/assets/1011202/5954093/ef794fc4-a7b8-11e4-8084-be399b1576de.png)

**Comment by sivaa** [comment]
This issue seems to be fixed already.
![image](https://cloud.githubusercontent.com/assets/2163422/5988728/d0a29048-a992-11e4-9e19-17dcb676f8e4.png)

**Comment by mudassir0909** [comment]
The whitespace had content in white color which is fixed right now
