### ISSUE TITLE
Removed Hardcoded vote and comments number value when window size is small

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/junction#95]
Looks like vote and comments number is hard coded when there window size is reduced.
Attached is screen shot for normal window and reduced window size.

![junction_comment](https://cloud.githubusercontent.com/assets/316253/5934198/bf859510-a6f1-11e4-98c1-a9b57f13ea3c.png)
![junction_comment](https://cloud.githubusercontent.com/assets/316253/5934205/dd08187e-a6f1-11e4-8e39-9ca2d720c61f.png)

**Comment by sivaa** [comment]
It happens on the mobile version too.

**Comment by theskumar** [comment]
This has been fixed now.
