### ISSUE TITLE
Tag based Filtering

### ISSUE THREAD

**Issue by sivaa** [pythonindia/junction#99]
![image](https://cloud.githubusercontent.com/assets/2163422/5954129/43e5c90c-a7b9-11e4-9027-232313f8ee1f.png)

If we click on these tags, it should filter the appropriate proposal sections or proposal types.

**Comment by theskumar** [comment]
Should we go with javascript or server-side solution.

**Comment by sivaa** [comment]
@theskumar Server side should be simple enough.

**Comment by theskumar** [comment]
Yeah. Thought so as we don't have a json api based interface and things are rendered server side.
